<!DOCTYPE html>
<html lang="en"><head>
<script src="p360_lecture_09.01_files/libs/clipboard/clipboard.min.js"></script>
<script src="p360_lecture_09.01_files/libs/quarto-html/tabby.min.js"></script>
<script src="p360_lecture_09.01_files/libs/quarto-html/popper.min.js"></script>
<script src="p360_lecture_09.01_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="p360_lecture_09.01_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="p360_lecture_09.01_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="p360_lecture_09.01_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Dr.&nbsp;Caleb Fowler">
  <title>CISP 360 Structured Programming</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="p360_lecture_09.01_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="p360_lecture_09.01_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="p360_lecture_09.01_files/libs/revealjs/dist/theme/quarto-99eeafcedac04850354b682963cedae3.css">
  <link rel="stylesheet" href="../styles/styles.css">
  <link href="p360_lecture_09.01_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="p360_lecture_09.01_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="p360_lecture_09.01_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="p360_lecture_09.01_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">CISP 360 Structured Programming</h1>
  <p class="subtitle">Introduction to C++</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Dr.&nbsp;Caleb Fowler 
</div>
</div>
</div>

</section>
<section id="last-time" class="slide level2">
<h2>Last Time</h2>
<ol type="1">
<li class="fragment"><strong>The While Loop</strong>: An entry-condition loop that keeps running as long as its condition is true. Initialize the loop control variable before the loop, test in the condition, update inside the body.</li>
<li class="fragment"><strong>Do-While and For Loops</strong>: Do-while is an exit-condition loop — it always runs at least once. For is a counter-controlled loop with init/condition/update in one line.</li>
<li class="fragment"><strong>Which Loop to Use</strong>: For a known count, use for. When it must run at least once, use do-while. For everything else, use while.</li>
</ol>
</section>
<section id="todays-agenda" class="slide level2">
<h2>Today’s Agenda</h2>
<ul>
<li>How the compiler works</li>
<li>The symbol table</li>
<li>Overflow and underflow</li>
<li>Data type conversion and casting</li>
<li>Signed vs unsigned variables</li>
<li>Fixed-width integers and size_t</li>
<li>Determining variable size</li>
</ul>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

</section>
<section>
<section id="how-the-compiler-works" class="title-slide slide level1 center">
<h1>How the Compiler Works</h1>

</section>
<section id="how-the-compiler-works-1" class="slide level2">
<h2>How the Compiler Works</h2>
<p>What happens when you press “build” in your IDE? The compiler transforms your source code through several distinct stages into an executable program. Understanding this process helps you debug faster and write better C++ code.</p>
<aside class="notes">
<p>Total slides: 11</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 1 -->
</section>
<section id="the-compilation-process-overview" class="slide level2">
<h2>The Compilation Process Overview</h2>
<p>The path from source code to a running program involves three major stages: preprocessing, compilation, and linking. Each stage processes your code in a specific way and produces intermediate output. Together, they transform human-readable C++ into machine-executable code.</p>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 2 -->
</section>
<section id="stage-1-preprocessing" class="slide level2">
<h2>Stage 1: Preprocessing</h2>
<p>The preprocessor runs before actual compilation and handles directives that start with <code>#</code>. It expands macros, inserts file contents from <code>#include</code> statements, and removes comments. The output is still C++ source code — just with all directives resolved.</p>
<!-- Slide 3 -->
</section>
<section id="preprocessing-directives" class="slide level2">
<h2>Preprocessing Directives</h2>
<ul>
<li><code>#include &lt;file&gt;</code>: Inserts the entire contents of a header file into your source. The preprocessor does not validate syntax.</li>
<li><code>#define NAME value</code>: Creates a textual substitution; every occurrence of NAME is replaced with value before compilation.</li>
<li><code>#ifdef</code> / <code>#if</code>: Conditionally includes or excludes code blocks based on whether symbols are defined.</li>
</ul>
<!-- Slide 4 -->
</section>
<section id="stage-2-compilation" class="slide level2">
<h2>Stage 2: Compilation</h2>
<p>The compiler takes preprocessed source code and performs syntax checking to verify it follows C++ grammar rules. It then translates valid code into assembly language or object code specific to your target processor. A single <code>.cpp</code> file becomes one <code>.o</code> (object) file.</p>
<!-- Slide 5 -->
</section>
<section id="what-the-compiler-checks" class="slide level2">
<h2>What the Compiler Checks</h2>
<ul>
<li><strong>Syntax</strong>: Does your code follow C++ grammar rules?</li>
<li><strong>Types</strong>: Do variable types match in assignments, function calls, and operations? C++ is statically typed — type mismatches are caught here, not at runtime.</li>
<li><strong>Scope and declarations</strong>: Are variables and functions declared before use? Do names conflict?</li>
</ul>
<!-- Slide 6 -->
</section>
<section id="stage-3-linking" class="slide level2">
<h2>Stage 3: Linking</h2>
<p>The linker takes multiple object files and combines them into one executable. It also resolves references to library functions. If a function is called but not defined anywhere, the linker reports an “undefined reference” error.</p>
<!-- Slide 7 -->
</section>
<section id="linking-how-it-works" class="slide level2">
<h2>Linking: How It Works</h2>
<ul>
<li><strong>Symbol resolution</strong>: The linker matches each function call to its definition across all object files and libraries.</li>
<li><strong>Library linking</strong>: Standard headers like <code>&lt;iostream&gt;</code> declare functions; the linker connects your calls to their implementations in the standard library.</li>
<li>If <code>math.o</code> is missing, linking fails with “undefined reference to add()” even though <code>main.cpp</code> compiled cleanly.</li>
</ul>
<!-- Slide 8 -->
</section>
<section id="why-this-matters-for-c" class="slide level2">
<h2>Why This Matters for C++</h2>
<p>C++ performs type checking and most error detection at compile time, not at runtime. Bugs are caught before you run the program. Compilation takes longer than interpreted languages, but the result is fast native code with no hidden runtime type checks.</p>
<!-- Slide 9 -->
</section>
<section id="compile-time-vs-runtime-errors" class="slide level2">
<h2>Compile-Time vs Runtime Errors</h2>
<p>C++ catches type mismatches, undefined references, and syntax errors during compilation. Languages like Python defer these checks to runtime — errors only appear when that code path executes. In C++, you find problems immediately during development.</p>
<!-- Slide 10 -->
</section>
<section id="summary" class="slide level2">
<h2>Summary</h2>
<p>The compiler transforms source code through preprocessing, compilation, and linking. Understanding these stages helps you interpret error messages and locate bugs faster.</p>
<!-- Slide 11 -->
</section>
<section id="appendix" class="slide level2">
<h2>Appendix</h2>
<!-- Appendix -->
</section>
<section id="common-practices" class="slide level2">
<h2>Common Practices</h2>
<ul>
<li>Enable compiler warnings with <code>-Wall -Wextra</code> (g++/clang); warnings often flag real bugs that still compile.</li>
<li>Place declarations in <code>.h</code> files and implementations in <code>.cpp</code> files to keep linking straightforward.</li>
<li>Use <code>#pragma once</code> or header guards to prevent duplicate includes that cause linker errors.</li>
</ul>
<!-- Appendix Slide 1 -->
</section>
<section id="common-mistakes" class="slide level2">
<h2>Common Mistakes</h2>
<ul>
<li>Including <code>.cpp</code> files instead of <code>.h</code> files causes multiple-definition linker errors.</li>
<li>Forgetting to link against a required library produces “undefined reference” errors at link time, not compile time.</li>
<li>Assuming a program is correct because it compiled — the compiler only checks syntax and types, not logic.</li>
</ul>
<!-- Appendix Slide 2 -->
</section>
<section id="more-examples" class="slide level2">
<h2>More Examples</h2>
<p>A function <code>add()</code> declared in <code>math.h</code> and defined in <code>math.cpp</code>: the preprocessor copies <code>math.h</code> into <code>main.cpp</code>, the compiler generates <code>main.o</code> and <code>math.o</code>, and the linker resolves the call. If <code>math.o</code> is omitted from the build command, linking fails — even though both source files compiled cleanly.</p>
<!-- Appendix Slide 3 -->
</section>
<section id="practice-problems" class="slide level2">
<h2>Practice Problems</h2>
<ol type="1">
<li>Split a simple program into two <code>.cpp</code> files. Compile each file separately, then link them manually.</li>
<li>Add a <code>#define</code> constant and observe how the preprocessor substitutes it before compilation.</li>
<li>Intentionally remove a function definition and observe the exact linker error message.</li>
</ol>
<!-- Appendix Slide 4 -->
</section>
<section id="ai-search-terms" class="slide level2">
<h2>AI Search Terms</h2>
<ul>
<li>“C++ compilation stages preprocessing compilation linking”</li>
<li>“C++ compiler type checking at compile time”</li>
<li>“linker errors undefined reference C++”</li>
<li>“header guards C++ pragma once”</li>
<li>“C++ static vs dynamic typing”</li>
</ul>
<!-- Appendix Slide 5 -->
</section>
<section id="questions-for-reflection" class="slide level2">
<h2>Questions for Reflection</h2>
<ul>
<li>Why does C++ have a separate linking stage when some languages skip it entirely?</li>
<li>How would your debugging process change if type errors were caught at runtime instead of compile time?</li>
<li>Why might a function compile successfully but still fail during linking?</li>
</ul>
<!-- Appendix Slide 6 -->
</section></section>
<section>
<section id="the-symbol-table" class="title-slide slide level1 center">
<h1>The Symbol Table</h1>

</section>
<section id="the-symbol-table-1" class="slide level2">
<h2>The Symbol Table</h2>
<p>What problems does the compiler face when tracking every identifier in your code, and how does it solve them? The symbol table is the compiler’s internal database that records every identifier — variable, function, or type — along with its name, data type, scope, and memory location. Understanding it helps you recognize compile-time errors and write code the compiler can reason about cleanly.</p>
<aside class="notes">
<p>Total slides: 9</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 1 -->
</section>
<section id="what-is-the-symbol-table" class="slide level2">
<h2>What Is the Symbol Table?</h2>
<p>The symbol table is a compiler-maintained record that maps identifiers to their properties. Every time you declare a variable, function, or type, the compiler adds an entry. This table drives type checking, scope resolution, error detection, and code generation.</p>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 2 -->
</section>
<section id="what-goes-in-the-symbol-table" class="slide level2">
<h2>What Goes in the Symbol Table?</h2>
<ul>
<li><strong>Name</strong>: The identifier as written in code (<code>count</code>, <code>processData</code>).</li>
<li><strong>Data type</strong>: The declared type (<code>int</code>, <code>double</code>, <code>string</code>) — used for type checking.</li>
<li><strong>Scope</strong>: Whether the identifier is local, global, or block-scoped — determines visibility.</li>
<li><strong>Memory location</strong>: Where the variable lives, or the entry point of a function.</li>
</ul>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 3 -->
</section>
<section id="how-the-compiler-uses-it" class="slide level2">
<h2>How the Compiler Uses It</h2>
<ul>
<li><strong>Type checking</strong>: When you assign <code>int x = "hello"</code>, the compiler checks the table and reports a type mismatch.</li>
<li><strong>Scope resolution</strong>: When you reference <code>count</code>, the compiler searches from innermost scope outward.</li>
<li><strong>Duplicate detection</strong>: If you declare the same variable twice in the same scope, the compiler finds the first entry and rejects the second.</li>
<li><strong>Code generation</strong>: The compiler uses addresses stored in the table to read and write each variable.</li>
</ul>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 4 -->
</section>
<section id="undeclared-variable-error" class="slide level2">
<h2>Undeclared Variable Error</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb1-1"><a href=""></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb1-2"><a href=""></a>    count <span class="op">=</span> <span class="dv">10</span><span class="op">;</span>   <span class="co">// Error: 'count' was not declared in this scope</span></span>
<span id="cb1-3"><a href=""></a>    <span class="cf">return</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb1-4"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The compiler searched the symbol table and found no entry for <code>count</code>. Declare it before you use it.</p>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 5 -->
</section>
<section id="redeclaration-error" class="slide level2">
<h2>Redeclaration Error</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb2-1"><a href=""></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb2-2"><a href=""></a>    <span class="dt">int</span> x <span class="op">=</span> <span class="dv">5</span><span class="op">;</span></span>
<span id="cb2-3"><a href=""></a>    <span class="dt">int</span> x <span class="op">=</span> <span class="dv">10</span><span class="op">;</span>   <span class="co">// Error: redeclaration of 'int x'</span></span>
<span id="cb2-4"><a href=""></a>    <span class="cf">return</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb2-5"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The compiler found <code>x</code> already in the symbol table for this scope. Each identifier can have only one entry per scope.</p>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 6 -->
</section>
<section id="type-mismatch-error" class="slide level2">
<h2>Type Mismatch Error</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb3-1"><a href=""></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb3-2"><a href=""></a>    <span class="dt">int</span> age <span class="op">=</span> <span class="dv">25</span><span class="op">;</span></span>
<span id="cb3-3"><a href=""></a>    age <span class="op">=</span> <span class="st">"twenty-five"</span><span class="op">;</span>  <span class="co">// Error: invalid conversion from 'const char*' to 'int'</span></span>
<span id="cb3-4"><a href=""></a>    <span class="cf">return</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb3-5"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The symbol table records <code>age</code> as type <code>int</code>. The compiler checks the incoming value’s type and rejects the assignment.</p>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 7 -->
</section>
<section id="scope-and-the-symbol-table" class="slide level2">
<h2>Scope and the Symbol Table</h2>
<p>Each scope (global, function, block) has its own region in the table. When you reference an identifier, the compiler searches from the innermost scope outward. A local variable with the same name as a global one shadows the global — the compiler finds the local entry first.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb4-1"><a href=""></a><span class="dt">int</span> x <span class="op">=</span> <span class="dv">5</span><span class="op">;</span>           <span class="co">// global</span></span>
<span id="cb4-2"><a href=""></a><span class="dt">void</span> func<span class="op">()</span> <span class="op">{</span></span>
<span id="cb4-3"><a href=""></a>    <span class="dt">int</span> x <span class="op">=</span> <span class="dv">10</span><span class="op">;</span>      <span class="co">// local — shadows global x</span></span>
<span id="cb4-4"><a href=""></a>    cout <span class="op">&lt;&lt;</span> x<span class="op">;</span>       <span class="co">// prints 10</span></span>
<span id="cb4-5"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 8 -->
</section>
<section id="summary-1" class="slide level2">
<h2>Summary</h2>
<p>The symbol table is the compiler’s record of every identifier: its name, type, scope, and location. Type mismatches, undeclared variables, and redeclarations all stem from symbol table violations — the compiler cannot build what it cannot track.</p>
<!-- Slide 9 -->
</section>
<section id="appendix-1" class="slide level2">
<h2>Appendix</h2>
<!-- Appendix -->
</section>
<section id="common-practices-1" class="slide level2">
<h2>Common Practices</h2>
<ul>
<li>Declare variables before use so the compiler can add them to the table before they are referenced.</li>
<li>Keep variables as local as possible — narrow scope reduces the number of entries in the table and makes code easier to reason about.</li>
<li>Avoid reusing the same name in nested scopes unless shadowing is intentional and clearly documented.</li>
</ul>
<!-- Appendix Slide 1 -->
</section>
<section id="common-mistakes-1" class="slide level2">
<h2>Common Mistakes</h2>
<ul>
<li>Writing <code>count = 5;</code> without a prior declaration — the symbol table has no entry and the compiler stops with an error.</li>
<li>Declaring the same variable twice in one scope — the table already has the entry and rejects the duplicate.</li>
<li>Accidentally shadowing a global variable with a local one of the same name, causing the global to silently go unused.</li>
</ul>
<!-- Appendix Slide 2 -->
</section>
<section id="more-examples-1" class="slide level2">
<h2>More Examples</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb5-1"><a href=""></a><span class="dt">void</span> process<span class="op">()</span> <span class="op">{</span></span>
<span id="cb5-2"><a href=""></a>    <span class="dt">int</span> result <span class="op">=</span> <span class="dv">0</span><span class="op">;</span>     <span class="co">// local — own symbol table entry</span></span>
<span id="cb5-3"><a href=""></a><span class="op">}</span></span>
<span id="cb5-4"><a href=""></a></span>
<span id="cb5-5"><a href=""></a><span class="dt">int</span> result <span class="op">=</span> <span class="dv">100</span><span class="op">;</span>       <span class="co">// global — separate entry; no conflict</span></span>
<span id="cb5-6"><a href=""></a></span>
<span id="cb5-7"><a href=""></a>vector<span class="op">&lt;</span><span class="dt">int</span><span class="op">&gt;</span> data<span class="op">;</span></span>
<span id="cb5-8"><a href=""></a>data<span class="op">.</span>push_back<span class="op">(</span><span class="st">"x"</span><span class="op">);</span>  <span class="co">// Error: table says data holds int, not string</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Appendix Slide 3 -->
</section>
<section id="practice-problems-1" class="slide level2">
<h2>Practice Problems</h2>
<ol type="1">
<li>Write a short program with a global and a local variable of the same name. Predict what the program will print.</li>
<li>Declare a function before defining it (forward declaration). Sketch the symbol table entries at the point of declaration.</li>
<li>Declare two variables with the same name in the same scope. Observe and explain the compiler error message.</li>
<li>Assign a string literal to an <code>int</code> variable without a cast. Read the error message and identify what type the table expected.</li>
</ol>
<!-- Appendix Slide 4 -->
</section>
<section id="ai-search-terms-1" class="slide level2">
<h2>AI Search Terms</h2>
<ul>
<li>“C++ symbol table compiler”</li>
<li>“undeclared identifier error C++”</li>
<li>“variable shadowing C++ scope”</li>
<li>“redeclaration error same scope”</li>
<li>“C++ scope resolution operator”</li>
</ul>
<!-- Appendix Slide 5 -->
</section>
<section id="questions-for-reflection-1" class="slide level2">
<h2>Questions for Reflection</h2>
<ul>
<li>Why does the compiler need a symbol table instead of re-scanning your code on every reference?</li>
<li>What happens to local symbol table entries when a function returns?</li>
<li>How does the linker use a version of the symbol table to match function calls across object files?</li>
</ul>
<!-- Appendix Slide 6 -->
</section></section>
<section>
<section id="overflow-and-underflow" class="title-slide slide level1 center">
<h1>Overflow and Underflow</h1>

</section>
<section id="overflow-and-underflow-1" class="slide level2">
<h2>Overflow and Underflow</h2>
<p>What happens when an integer exceeds its maximum value or drops below its minimum? These silent errors produce wrong results with no warning. This section covers how overflow and underflow work and how to avoid them.</p>
<aside class="notes">
<p>Total slides: 9</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 1 -->
</section>
<section id="what-is-integer-overflow" class="slide level2">
<h2>What Is Integer Overflow?</h2>
<p>Overflow occurs when a value exceeds the maximum representable value for its type. For <strong>unsigned</strong> integers, the value wraps back to zero — this behavior is well-defined. For <strong>signed</strong> integers, overflow is undefined behavior in C++, meaning the program may do anything.</p>
<aside class="notes">
<p>Emphasize: signed overflow = undefined behavior. The program may appear to work, crash, or produce incorrect results silently.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 2 -->
</section>
<section id="what-is-integer-underflow" class="slide level2">
<h2>What Is Integer Underflow?</h2>
<p>Underflow occurs when a value drops below the minimum representable value for its type. For <strong>unsigned</strong> integers, decrementing past zero wraps to the maximum value — also well-defined. For <strong>signed</strong> integers, going below the minimum is again undefined behavior. Floating-point underflow is different: very small values round to zero rather than wrapping.</p>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 3 -->
</section>
<section id="integer-ranges" class="slide level2">
<h2>Integer Ranges</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Type</th>
<th>Minimum</th>
<th>Maximum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>short</code></td>
<td>−32,768</td>
<td>32,767</td>
</tr>
<tr class="even">
<td><code>int</code></td>
<td>−2,147,483,648</td>
<td>2,147,483,647</td>
</tr>
<tr class="odd">
<td><code>long</code></td>
<td>−9,223,372,036,854,775,808</td>
<td>9,223,372,036,854,775,807</td>
</tr>
<tr class="even">
<td><code>unsigned int</code></td>
<td>0</td>
<td>4,294,967,295</td>
</tr>
<tr class="odd">
<td><code>unsigned short</code></td>
<td>0</td>
<td>65,535</td>
</tr>
</tbody>
</table>
<p>These values are platform-dependent. Use <code>&lt;limits&gt;</code> rather than hardcoding them.</p>
<aside class="notes">
<p>[Graphic suggestion: Visual number line showing where wrap-around occurs for a short.]</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 4 -->
</section>
<section id="querying-limits-at-runtime" class="slide level2">
<h2>Querying Limits at Runtime</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb6-1"><a href=""></a><span class="pp">#include </span><span class="im">&lt;limits&gt;</span></span>
<span id="cb6-2"><a href=""></a><span class="pp">#include </span><span class="im">&lt;iostream&gt;</span></span>
<span id="cb6-3"><a href=""></a><span class="kw">using</span> <span class="kw">namespace</span> std<span class="op">;</span></span>
<span id="cb6-4"><a href=""></a></span>
<span id="cb6-5"><a href=""></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb6-6"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"int max:   "</span> <span class="op">&lt;&lt;</span> numeric_limits<span class="op">&lt;</span><span class="dt">int</span><span class="op">&gt;::</span>max<span class="op">()</span>          <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb6-7"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"int min:   "</span> <span class="op">&lt;&lt;</span> numeric_limits<span class="op">&lt;</span><span class="dt">int</span><span class="op">&gt;::</span>min<span class="op">()</span>          <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb6-8"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"short max: "</span> <span class="op">&lt;&lt;</span> numeric_limits<span class="op">&lt;</span><span class="dt">short</span><span class="op">&gt;::</span>max<span class="op">()</span>        <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb6-9"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"uint max:  "</span> <span class="op">&lt;&lt;</span> numeric_limits<span class="op">&lt;</span><span class="dt">unsigned</span> <span class="dt">int</span><span class="op">&gt;::</span>max<span class="op">()</span> <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb6-10"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>numeric_limits&lt;T&gt;</code> from <code>&lt;limits&gt;</code> is the portable way to query exact ranges for any type.</p>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 5 -->
</section>
<section id="overflow-in-action" class="slide level2">
<h2>Overflow in Action</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb7-1"><a href=""></a><span class="dt">short</span> s <span class="op">=</span> <span class="dv">32767</span><span class="op">;</span>    <span class="co">// max value for short</span></span>
<span id="cb7-2"><a href=""></a>s<span class="op">++;</span></span>
<span id="cb7-3"><a href=""></a>cout <span class="op">&lt;&lt;</span> s<span class="op">;</span>          <span class="co">// -32768  (wraps to minimum)</span></span>
<span id="cb7-4"><a href=""></a></span>
<span id="cb7-5"><a href=""></a><span class="dt">unsigned</span> <span class="dt">int</span> u <span class="op">=</span> <span class="dv">4294967295</span><span class="op">;</span>   <span class="co">// max for unsigned int</span></span>
<span id="cb7-6"><a href=""></a>u<span class="op">++;</span></span>
<span id="cb7-7"><a href=""></a>cout <span class="op">&lt;&lt;</span> u<span class="op">;</span>          <span class="co">// 0  (wraps to zero)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Unsigned wrap-around is predictable. Do not rely on signed wrap-around — the behavior is undefined and the compiler may optimize it away.</p>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 6 -->
</section>
<section id="detecting-overflow-before-it-happens" class="slide level2">
<h2>Detecting Overflow Before It Happens</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb8-1"><a href=""></a><span class="pp">#include </span><span class="im">&lt;limits&gt;</span></span>
<span id="cb8-2"><a href=""></a><span class="kw">using</span> <span class="kw">namespace</span> std<span class="op">;</span></span>
<span id="cb8-3"><a href=""></a></span>
<span id="cb8-4"><a href=""></a><span class="dt">bool</span> wouldOverflow<span class="op">(</span><span class="dt">int</span> a<span class="op">,</span> <span class="dt">int</span> b<span class="op">)</span> <span class="op">{</span></span>
<span id="cb8-5"><a href=""></a>    <span class="cf">return</span> <span class="op">(</span>b <span class="op">&gt;</span> <span class="dv">0</span> <span class="op">&amp;&amp;</span> a <span class="op">&gt;</span> numeric_limits<span class="op">&lt;</span><span class="dt">int</span><span class="op">&gt;::</span>max<span class="op">()</span> <span class="op">-</span> b<span class="op">);</span></span>
<span id="cb8-6"><a href=""></a><span class="op">}</span></span>
<span id="cb8-7"><a href=""></a></span>
<span id="cb8-8"><a href=""></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb8-9"><a href=""></a>    <span class="cf">if</span> <span class="op">(</span>wouldOverflow<span class="op">(</span><span class="dv">2000000000</span><span class="op">,</span> <span class="dv">200000000</span><span class="op">))</span> <span class="op">{</span></span>
<span id="cb8-10"><a href=""></a>        cout <span class="op">&lt;&lt;</span> <span class="st">"Overflow detected — operation skipped.</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb8-11"><a href=""></a>    <span class="op">}</span></span>
<span id="cb8-12"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Check before the operation, not after. Once undefined behavior occurs, the result cannot be trusted.</p>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 7 -->
</section>
<section id="prevention-strategies" class="slide level2">
<h2>Prevention Strategies</h2>
<ul>
<li>Use a larger type (<code>long long</code>) when calculations may exceed <code>int</code> range.</li>
<li>Validate user input against type limits before performing arithmetic.</li>
<li>Treat compiler warnings about integer conversion seriously — they often indicate overflow risk.</li>
<li>For unsigned loops with decrement, verify the loop terminates before reaching zero.</li>
</ul>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 8 -->
</section>
<section id="summary-2" class="slide level2">
<h2>Summary</h2>
<p>Unsigned integer overflow and underflow wrap around predictably. Signed integer overflow is undefined behavior and must be prevented — not merely detected after the fact. Use <code>numeric_limits&lt;T&gt;</code> to query ranges and choose the right type for your data.</p>
<!-- Slide 9 -->
</section>
<section id="appendix-2" class="slide level2">
<h2>Appendix</h2>
<!-- Appendix -->
</section>
<section id="common-practices-2" class="slide level2">
<h2>Common Practices</h2>
<ul>
<li>Include <code>&lt;limits&gt;</code> and use <code>numeric_limits&lt;T&gt;::max()</code> / <code>numeric_limits&lt;T&gt;::min()</code> — never hardcode type bounds.</li>
<li>Perform overflow checks before arithmetic, not after.</li>
<li>Prefer <code>long long</code> for accumulations and counters that may grow large.</li>
<li>Use unsigned types only when negative values are impossible and wrap-around is understood.</li>
</ul>
<!-- Appendix Slide 1 -->
</section>
<section id="common-mistakes-2" class="slide level2">
<h2>Common Mistakes</h2>
<ul>
<li>Assuming signed overflow wraps reliably — the standard gives no guarantee, and optimizing compilers exploit this.</li>
<li>Using <code>unsigned char</code> or <code>unsigned short</code> as a loop counter that decrements to zero — decrementing past zero wraps to a large value and creates an infinite loop.</li>
<li>Ignoring compiler warnings about narrowing conversions that can silently lose the high bits of a value.</li>
</ul>
<!-- Appendix Slide 2 -->
</section>
<section id="more-examples-2" class="slide level2">
<h2>More Examples</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb9-1"><a href=""></a><span class="co">// Signed multiplication overflow</span></span>
<span id="cb9-2"><a href=""></a><span class="dt">int</span> x <span class="op">=</span> <span class="dv">100000</span><span class="op">;</span></span>
<span id="cb9-3"><a href=""></a><span class="dt">int</span> y <span class="op">=</span> <span class="dv">100000</span><span class="op">;</span></span>
<span id="cb9-4"><a href=""></a><span class="dt">int</span> z <span class="op">=</span> x <span class="op">*</span> y<span class="op">;</span>   <span class="co">// Undefined behavior — exceeds INT_MAX</span></span>
<span id="cb9-5"><a href=""></a></span>
<span id="cb9-6"><a href=""></a><span class="co">// Unsigned char wrap-around</span></span>
<span id="cb9-7"><a href=""></a><span class="dt">unsigned</span> <span class="dt">char</span> c <span class="op">=</span> <span class="dv">255</span><span class="op">;</span></span>
<span id="cb9-8"><a href=""></a>c <span class="op">+=</span> <span class="dv">2</span><span class="op">;</span></span>
<span id="cb9-9"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="op">(</span><span class="dt">int</span><span class="op">)</span>c<span class="op">;</span>  <span class="co">// prints 1 (wraps: 255 + 2 = 257, 257 % 256 = 1)</span></span>
<span id="cb9-10"><a href=""></a></span>
<span id="cb9-11"><a href=""></a><span class="co">// Float underflow</span></span>
<span id="cb9-12"><a href=""></a><span class="dt">float</span> f <span class="op">=</span> <span class="fl">1e-50</span><span class="bu">f</span><span class="op">;</span></span>
<span id="cb9-13"><a href=""></a>cout <span class="op">&lt;&lt;</span> f<span class="op">;</span>       <span class="co">// prints 0.0 (too small to represent)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Appendix Slide 3 -->
</section>
<section id="practice-problems-2" class="slide level2">
<h2>Practice Problems</h2>
<ol type="1">
<li>Write a function that safely adds two <code>int</code> values, returning <code>false</code> if overflow would occur.</li>
<li>Declare an <code>unsigned char</code> loop counter and count from 0 to 300. Observe and explain the output.</li>
<li>Use <code>numeric_limits</code> to print the min and max for <code>short</code>, <code>int</code>, <code>long</code>, and their unsigned variants.</li>
<li>Demonstrate the difference in behavior between signed and unsigned overflow with a short code example.</li>
</ol>
<!-- Appendix Slide 4 -->
</section>
<section id="ai-search-terms-2" class="slide level2">
<h2>AI Search Terms</h2>
<ul>
<li>“C++ signed integer overflow undefined behavior”</li>
<li>“C++ unsigned integer wraparound modulo”</li>
<li>“C++ numeric_limits max min”</li>
<li>“C++ detect overflow before addition”</li>
<li>“C++ float underflow denormalized”</li>
</ul>
<!-- Appendix Slide 5 -->
</section>
<section id="questions-for-reflection-2" class="slide level2">
<h2>Questions for Reflection</h2>
<ul>
<li>Why does the C++ standard declare signed overflow undefined rather than specifying wrap-around?</li>
<li>When would unsigned wrap-around be intentional and useful in a program?</li>
<li>How would you redesign a financial calculation to prevent overflow without switching to a different language?</li>
</ul>
<!-- Appendix Slide 6 -->
</section></section>
<section>
<section id="whats-the-output-overflow-underflow" class="title-slide slide level1 center">
<h1>What’s the Output? — Overflow &amp; Underflow</h1>

</section>
<section id="whats-the-output-overflow-underflow-1" class="slide level2">
<h2>What’s the Output? — Overflow &amp; Underflow</h2>
<p>Overflow and underflow produce values outside a type’s representable range. Before running each example, predict the output — then check your reasoning against the answer. Getting the prediction wrong is the point: it reveals exactly where your mental model needs work.</p>
<aside class="notes">
<p>Total slides: 11</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 1 -->
</section>
<section id="how-to-use-these-exercises" class="slide level2">
<h2>How to Use These Exercises</h2>
<p>Read the code, predict what prints, then advance to the answer slide. If your prediction was wrong, focus on the answer explanation — not just the output, but why that output occurs.</p>
<!-- Slide 2 -->
</section>
<section id="whats-the-output-short-overflow" class="slide level2">
<h2>What’s the Output? — Short Overflow</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb10-1"><a href=""></a><span class="pp">#include </span><span class="im">&lt;iostream&gt;</span></span>
<span id="cb10-2"><a href=""></a><span class="kw">using</span> <span class="kw">namespace</span> std<span class="op">;</span></span>
<span id="cb10-3"><a href=""></a></span>
<span id="cb10-4"><a href=""></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb10-5"><a href=""></a>    <span class="dt">short</span> s <span class="op">=</span> <span class="dv">32767</span><span class="op">;</span></span>
<span id="cb10-6"><a href=""></a>    s<span class="op">++;</span></span>
<span id="cb10-7"><a href=""></a>    cout <span class="op">&lt;&lt;</span> s <span class="op">&lt;&lt;</span> endl<span class="op">;</span></span>
<span id="cb10-8"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Answer: -32768</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 3 -->
</section>
<section id="output-short-overflow" class="slide level2">
<h2>Output — Short Overflow</h2>
<pre><code>-32768</code></pre>
<p>A <code>short</code> holds values from −32,768 to 32,767. Incrementing 32,767 moves past the maximum. The bit pattern rolls over to the minimum value, −32,768. This is undefined behavior for signed types — many compilers produce this result on x86, but it is not guaranteed.</p>
<aside class="notes">
<p>Emphasize: signed overflow = undefined behavior. Students often think “it wraps, so it’s fine.” It is not.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 4 -->
</section>
<section id="whats-the-output-unsigned-underflow" class="slide level2">
<h2>What’s the Output? — Unsigned Underflow</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb12-1"><a href=""></a><span class="pp">#include </span><span class="im">&lt;iostream&gt;</span></span>
<span id="cb12-2"><a href=""></a><span class="kw">using</span> <span class="kw">namespace</span> std<span class="op">;</span></span>
<span id="cb12-3"><a href=""></a></span>
<span id="cb12-4"><a href=""></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb12-5"><a href=""></a>    <span class="dt">unsigned</span> <span class="dt">int</span> u <span class="op">=</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb12-6"><a href=""></a>    u<span class="op">--;</span></span>
<span id="cb12-7"><a href=""></a>    cout <span class="op">&lt;&lt;</span> u <span class="op">&lt;&lt;</span> endl<span class="op">;</span></span>
<span id="cb12-8"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Answer: 4294967295</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 5 -->
</section>
<section id="output-unsigned-underflow" class="slide level2">
<h2>Output — Unsigned Underflow</h2>
<pre><code>4294967295</code></pre>
<p>Decrementing an <code>unsigned int</code> past zero wraps to the maximum value. On a 32-bit system, that is 2³² − 1 = 4,294,967,295. Unlike signed overflow, unsigned wraparound is <strong>well-defined</strong> in C++ — this behavior is guaranteed.</p>
<aside class="notes">
<p>Contrast with slide 3: unsigned wrap-around is safe and predictable; signed wrap-around is undefined. This distinction matters.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 6 -->
</section>
<section id="whats-the-output-int_max-1" class="slide level2">
<h2>What’s the Output? — INT_MAX + 1</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb14-1"><a href=""></a><span class="pp">#include </span><span class="im">&lt;iostream&gt;</span></span>
<span id="cb14-2"><a href=""></a><span class="pp">#include </span><span class="im">&lt;climits&gt;</span></span>
<span id="cb14-3"><a href=""></a><span class="kw">using</span> <span class="kw">namespace</span> std<span class="op">;</span></span>
<span id="cb14-4"><a href=""></a></span>
<span id="cb14-5"><a href=""></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb14-6"><a href=""></a>    <span class="dt">int</span> x <span class="op">=</span> INT_MAX<span class="op">;</span></span>
<span id="cb14-7"><a href=""></a>    cout <span class="op">&lt;&lt;</span> x <span class="op">+</span> <span class="dv">1</span> <span class="op">&lt;&lt;</span> endl<span class="op">;</span></span>
<span id="cb14-8"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Answer: undefined behavior — on most x86 compilers this prints -2147483648, but it is NOT guaranteed.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 7 -->
</section>
<section id="output-int_max-1" class="slide level2">
<h2>Output — INT_MAX + 1</h2>
<pre><code>-2147483648   ← common result, not guaranteed</code></pre>
<p>Adding 1 to <code>INT_MAX</code> (2,147,483,647) causes signed integer overflow — undefined behavior. Many compilers produce −2,147,483,648 due to two’s complement wrap, but an optimizer may eliminate the operation entirely or produce something else. Never rely on this.</p>
<aside class="notes">
<p>Good moment to ask: “If the output is undefined, why does it appear consistent?” Answer: modern x86 hardware happens to wrap, but the compiler isn’t obligated to use that behavior.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 8 -->
</section>
<section id="whats-the-output-float-underflow" class="slide level2">
<h2>What’s the Output? — Float Underflow</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb16-1"><a href=""></a><span class="pp">#include </span><span class="im">&lt;iostream&gt;</span></span>
<span id="cb16-2"><a href=""></a><span class="pp">#include </span><span class="im">&lt;iomanip&gt;</span></span>
<span id="cb16-3"><a href=""></a><span class="kw">using</span> <span class="kw">namespace</span> std<span class="op">;</span></span>
<span id="cb16-4"><a href=""></a></span>
<span id="cb16-5"><a href=""></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb16-6"><a href=""></a>    <span class="dt">float</span> f <span class="op">=</span> <span class="fl">1e-50</span><span class="bu">f</span><span class="op">;</span></span>
<span id="cb16-7"><a href=""></a>    cout <span class="op">&lt;&lt;</span> fixed <span class="op">&lt;&lt;</span> setprecision<span class="op">(</span><span class="dv">10</span><span class="op">)</span> <span class="op">&lt;&lt;</span> f <span class="op">&lt;&lt;</span> endl<span class="op">;</span></span>
<span id="cb16-8"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Answer: 0.0000000000</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 9 -->
</section>
<section id="output-float-underflow" class="slide level2">
<h2>Output — Float Underflow</h2>
<pre><code>0.0000000000</code></pre>
<p>The smallest normalized <code>float</code> is approximately 1.18 × 10⁻³⁸. The value 1 × 10⁻⁵⁰ is far below that range and rounds to zero. Floating-point underflow rounds to zero rather than wrapping — precision is lost silently. No error, no warning.</p>
<aside class="notes">
<p>Float underflow is gradual: the value becomes 0.0 without crashing. Contrast with integer underflow. Practical risk: silent loss of precision in scientific or financial calculations.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 10 -->
</section>
<section id="pattern-what-to-watch-for" class="slide level2">
<h2>Pattern: What to Watch For</h2>
<ul>
<li><strong>Signed types</strong>: never exceed <code>INT_MAX</code> or go below <code>INT_MIN</code> — the behavior is undefined.</li>
<li><strong>Unsigned types</strong>: expect wrap-around; whether that is a bug depends on intent.</li>
<li><strong>Float</strong>: very small results silently become zero — check for underflow in precision-sensitive code.</li>
</ul>
<!-- Slide 11 -->
</section>
<section id="summary-3" class="slide level2">
<h2>Summary</h2>
<p>Signed integer overflow is undefined — do not rely on wrap-around. Unsigned wrap-around is defined and predictable. Floating-point underflow rounds to zero silently. All three require awareness and preventive design.</p>
<!-- Slide 11 -->
</section>
<section id="appendix-3" class="slide level2">
<h2>Appendix</h2>
<!-- Appendix -->
</section>
<section id="common-practices-3" class="slide level2">
<h2>Common Practices</h2>
<ul>
<li>Use <code>numeric_limits&lt;T&gt;::max()</code> and <code>min()</code> to check values before operations that might overflow.</li>
<li>Treat signed and unsigned overflow differently — they have different rules and different risks.</li>
<li>Add range-checking to input validation when values will be used in arithmetic.</li>
</ul>
<!-- Appendix Slide 1 -->
</section>
<section id="common-mistakes-3" class="slide level2">
<h2>Common Mistakes</h2>
<ul>
<li>Assuming signed overflow wraps reliably across all compilers — it does not.</li>
<li>Using <code>unsigned</code> to “avoid” negatives but not accounting for underflow wrap when decrementing.</li>
<li>Ignoring floating-point underflow because no exception is raised — silent precision loss is a real bug.</li>
</ul>
<!-- Appendix Slide 2 -->
</section>
<section id="more-examples-3" class="slide level2">
<h2>More Examples</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb18-1"><a href=""></a><span class="dt">unsigned</span> <span class="dt">char</span> c <span class="op">=</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb18-2"><a href=""></a>c<span class="op">--;</span></span>
<span id="cb18-3"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="op">(</span><span class="dt">int</span><span class="op">)</span>c<span class="op">;</span>   <span class="co">// 255 (wraps to max for unsigned char)</span></span>
<span id="cb18-4"><a href=""></a></span>
<span id="cb18-5"><a href=""></a><span class="dt">unsigned</span> <span class="dt">char</span> c2 <span class="op">=</span> <span class="dv">255</span><span class="op">;</span></span>
<span id="cb18-6"><a href=""></a>c2 <span class="op">+=</span> <span class="dv">2</span><span class="op">;</span></span>
<span id="cb18-7"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="op">(</span><span class="dt">int</span><span class="op">)</span>c2<span class="op">;</span>  <span class="co">// 1 (wraps: 255 + 2 = 257, 257 % 256 = 1)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Appendix Slide 3 -->
</section>
<section id="practice-problems-3" class="slide level2">
<h2>Practice Problems</h2>
<ol type="1">
<li>What does this print? <code>short s = -32768; s--; cout &lt;&lt; s;</code></li>
<li>Write a safe increment function for <code>int</code> that prints an error instead of overflowing.</li>
<li>Predict the output: <code>unsigned int x = 1; cout &lt;&lt; (x - 2);</code></li>
<li>What is the minimum positive <code>float</code> your system can represent? Use <code>&lt;limits&gt;</code> to find out.</li>
</ol>
<!-- Appendix Slide 4 -->
</section>
<section id="ai-search-terms-3" class="slide level2">
<h2>AI Search Terms</h2>
<ul>
<li>“C++ signed integer overflow undefined behavior”</li>
<li>“C++ unsigned wraparound well-defined”</li>
<li>“C++ INT_MAX climits”</li>
<li>“C++ float underflow smallest value”</li>
<li>“C++ numeric_limits float min”</li>
</ul>
<!-- Appendix Slide 5 -->
</section>
<section id="questions-for-reflection-3" class="slide level2">
<h2>Questions for Reflection</h2>
<ul>
<li>Why is signed overflow undefined but unsigned overflow well-defined?</li>
<li>How would you build a test suite to catch overflow bugs in a financial calculation library?</li>
<li>What strategy would you use to debug a program that silently produces wrong numeric results?</li>
</ul>
<!-- Appendix Slide 6 -->
</section></section>
<section>
<section id="data-type-conversion-and-type-casting" class="title-slide slide level1 center">
<h1>Data Type Conversion and Type Casting</h1>

</section>
<section id="data-type-conversion-and-type-casting-1" class="slide level2">
<h2>Data Type Conversion and Type Casting</h2>
<p>When should we convert between numeric types, and what are the safe and unsafe ways to do it? C++ converts between types automatically in some cases, and lets you force conversion in others. Both paths have traps.</p>
<aside class="notes">
<p>Total slides: 11</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 1 -->
</section>
<section id="what-is-type-conversion" class="slide level2">
<h2>What Is Type Conversion?</h2>
<p>Type conversion occurs when a value of one type is used where a different type is expected. C++ handles this two ways: <strong>implicitly</strong> (automatically, without your input) and <strong>explicitly</strong> (through a cast you write). The distinction matters because implicit conversions can hide bugs.</p>
<!-- Slide 2 -->
</section>
<section id="implicit-conversion-promotion" class="slide level2">
<h2>Implicit Conversion: Promotion</h2>
<p>Promotion happens when a smaller type is assigned to a larger type. No data is lost. C++ performs this automatically.</p>
<ul>
<li><code>char</code> → <code>int</code> → <code>long</code> → <code>double</code> (widening)</li>
<li>Occurs in assignments, arithmetic expressions, and function calls</li>
</ul>
<!-- Slide 3 -->
</section>
<section id="implicit-promotion-examples" class="slide level2">
<h2>Implicit Promotion — Examples</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb19-1"><a href=""></a><span class="dt">int</span> x <span class="op">=</span> <span class="dv">5</span><span class="op">;</span></span>
<span id="cb19-2"><a href=""></a><span class="dt">double</span> y <span class="op">=</span> x<span class="op">;</span>        <span class="co">// int promoted to double; y = 5.0</span></span>
<span id="cb19-3"><a href=""></a></span>
<span id="cb19-4"><a href=""></a><span class="dt">char</span> c <span class="op">=</span> <span class="ch">'A'</span><span class="op">;</span></span>
<span id="cb19-5"><a href=""></a><span class="dt">int</span> val <span class="op">=</span> c<span class="op">;</span>         <span class="co">// char promoted to int; val = 65</span></span>
<span id="cb19-6"><a href=""></a></span>
<span id="cb19-7"><a href=""></a><span class="dt">int</span> a <span class="op">=</span> <span class="dv">10</span><span class="op">;</span></span>
<span id="cb19-8"><a href=""></a><span class="dt">double</span> r <span class="op">=</span> a <span class="op">/</span> <span class="fl">2.0</span><span class="op">;</span>  <span class="co">// a promoted before division; r = 5.0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Slide 4 -->
</section>
<section id="implicit-conversion-narrowing" class="slide level2">
<h2>Implicit Conversion: Narrowing</h2>
<p>Narrowing happens when a larger type is assigned to a smaller type. Data loss is likely. The compiler may warn but will not always stop you.</p>
<ul>
<li><code>double</code> → <code>int</code>: decimal part is truncated, not rounded</li>
<li><code>int</code> → <code>short</code>: high bits may be lost</li>
<li><code>long</code> → <code>int</code>: same risk</li>
</ul>
<!-- Slide 5 -->
</section>
<section id="narrowing-examples" class="slide level2">
<h2>Narrowing — Examples</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb20-1"><a href=""></a><span class="dt">double</span> x <span class="op">=</span> <span class="fl">3.7</span><span class="op">;</span></span>
<span id="cb20-2"><a href=""></a><span class="dt">int</span> y <span class="op">=</span> x<span class="op">;</span>             <span class="co">// Warning: y = 3 (decimal discarded)</span></span>
<span id="cb20-3"><a href=""></a></span>
<span id="cb20-4"><a href=""></a><span class="dt">long</span> bigNum <span class="op">=</span> <span class="dv">100000</span><span class="op">;</span></span>
<span id="cb20-5"><a href=""></a><span class="dt">short</span> s <span class="op">=</span> bigNum<span class="op">;</span>      <span class="co">// Warning: may overflow</span></span>
<span id="cb20-6"><a href=""></a></span>
<span id="cb20-7"><a href=""></a><span class="dt">int</span> a <span class="op">=</span> <span class="dv">7</span><span class="op">;</span></span>
<span id="cb20-8"><a href=""></a><span class="dt">int</span> b <span class="op">=</span> <span class="dv">2</span><span class="op">;</span></span>
<span id="cb20-9"><a href=""></a><span class="dt">int</span> result <span class="op">=</span> a <span class="op">/</span> b<span class="op">;</span>    <span class="co">// result = 3, not 3.5</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Slide 6 -->
</section>
<section id="c-style-casts" class="slide level2">
<h2>C-Style Casts</h2>
<p>C-style syntax: <code>(TargetType)value</code>. Works, but is not recommended in modern C++.</p>
<ul>
<li>Hard to search for in a large codebase</li>
<li>Hides intent — it’s not clear what kind of conversion is happening</li>
<li>Performs dangerous conversions without warning</li>
<li>Carried over from C; you will see it in older code</li>
</ul>
<!-- Slide 7 -->
</section>
<section id="static_cast-the-c-way" class="slide level2">
<h2>static_cast: The C++ Way</h2>
<p><code>static_cast&lt;TargetType&gt;(value)</code> is the preferred cast for numeric conversion. It makes your intent explicit and is easy to find with a search. Use it any time you need an intentional narrowing or explicit promotion.</p>
<!-- Slide 8 -->
</section>
<section id="static_cast-examples" class="slide level2">
<h2>static_cast — Examples</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb21-1"><a href=""></a><span class="dt">double</span> x <span class="op">=</span> <span class="fl">3.7</span><span class="op">;</span></span>
<span id="cb21-2"><a href=""></a><span class="dt">int</span> y <span class="op">=</span> <span class="kw">static_cast</span><span class="op">&lt;</span><span class="dt">int</span><span class="op">&gt;(</span>x<span class="op">);</span>              <span class="co">// explicit truncation; y = 3</span></span>
<span id="cb21-3"><a href=""></a></span>
<span id="cb21-4"><a href=""></a><span class="dt">int</span> dividend <span class="op">=</span> <span class="dv">7</span><span class="op">;</span></span>
<span id="cb21-5"><a href=""></a><span class="dt">int</span> divisor <span class="op">=</span> <span class="dv">2</span><span class="op">;</span></span>
<span id="cb21-6"><a href=""></a><span class="dt">double</span> r <span class="op">=</span> <span class="kw">static_cast</span><span class="op">&lt;</span><span class="dt">double</span><span class="op">&gt;(</span>dividend<span class="op">)</span> <span class="op">/</span> divisor<span class="op">;</span>  <span class="co">// r = 3.5</span></span>
<span id="cb21-7"><a href=""></a></span>
<span id="cb21-8"><a href=""></a><span class="dt">char</span> letter <span class="op">=</span> <span class="ch">'Z'</span><span class="op">;</span></span>
<span id="cb21-9"><a href=""></a><span class="dt">int</span> ascii <span class="op">=</span> <span class="kw">static_cast</span><span class="op">&lt;</span><span class="dt">int</span><span class="op">&gt;(</span>letter<span class="op">);</span>     <span class="co">// ascii = 90</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Slide 9 -->
</section>
<section id="when-to-cast-and-when-not-to" class="slide level2">
<h2>When to Cast and When Not To</h2>
<p>Use a cast to express intent — when you know truncation or conversion is correct. Do not cast to silence compiler warnings without fixing the underlying mismatch. A cast that hides a narrowing bug is worse than the warning it suppressed.</p>
<!-- Slide 10 -->
</section>
<section id="summary-4" class="slide level2">
<h2>Summary</h2>
<p>Implicit promotion is safe and automatic. Narrowing loses data — use <code>static_cast&lt;&gt;</code> to make it explicit and intentional. Never cast just to silence a warning; the warning usually means there is a real issue to address.</p>
<!-- Slide 11 -->
</section>
<section id="appendix-4" class="slide level2">
<h2>Appendix</h2>
<!-- Appendix -->
</section>
<section id="common-practices-4" class="slide level2">
<h2>Common Practices</h2>
<ul>
<li>Use <code>static_cast&lt;&gt;</code> for all intentional numeric conversions in C++.</li>
<li>Prefer implicit promotion (small → large); be explicit and deliberate with narrowing.</li>
<li>When mixing integer and floating-point in division, cast one operand to <code>double</code> to preserve precision.</li>
</ul>
<!-- Appendix Slide 1 -->
</section>
<section id="common-mistakes-4" class="slide level2">
<h2>Common Mistakes</h2>
<ul>
<li>Integer division: <code>7 / 2</code> returns <code>3</code>, not <code>3.5</code>. Cast at least one operand.</li>
<li>Silent narrowing: assigning a <code>double</code> to an <code>int</code> loses the decimal without an error.</li>
<li>Using a C-style cast in new code — <code>static_cast&lt;&gt;</code> is preferred and easier to review.</li>
</ul>
<!-- Appendix Slide 2 -->
</section>
<section id="more-examples-4" class="slide level2">
<h2>More Examples</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb22-1"><a href=""></a><span class="co">// Correct way to get floating-point average</span></span>
<span id="cb22-2"><a href=""></a><span class="dt">int</span> total <span class="op">=</span> <span class="dv">15</span><span class="op">,</span> count <span class="op">=</span> <span class="dv">4</span><span class="op">;</span></span>
<span id="cb22-3"><a href=""></a><span class="dt">double</span> avg <span class="op">=</span> <span class="kw">static_cast</span><span class="op">&lt;</span><span class="dt">double</span><span class="op">&gt;(</span>total<span class="op">)</span> <span class="op">/</span> count<span class="op">;</span>  <span class="co">// 3.75</span></span>
<span id="cb22-4"><a href=""></a></span>
<span id="cb22-5"><a href=""></a><span class="co">// Extracting cents from a price</span></span>
<span id="cb22-6"><a href=""></a><span class="dt">double</span> price <span class="op">=</span> <span class="fl">19.99</span><span class="op">;</span></span>
<span id="cb22-7"><a href=""></a><span class="dt">int</span> cents <span class="op">=</span> <span class="kw">static_cast</span><span class="op">&lt;</span><span class="dt">int</span><span class="op">&gt;(</span>price <span class="op">*</span> <span class="dv">100</span><span class="op">)</span> <span class="op">%</span> <span class="dv">100</span><span class="op">;</span>  <span class="co">// 99</span></span>
<span id="cb22-8"><a href=""></a></span>
<span id="cb22-9"><a href=""></a><span class="co">// Explicit comparison of mixed types</span></span>
<span id="cb22-10"><a href=""></a><span class="dt">int</span> a <span class="op">=</span> <span class="dv">5</span><span class="op">;</span></span>
<span id="cb22-11"><a href=""></a><span class="dt">double</span> b <span class="op">=</span> <span class="fl">5.5</span><span class="op">;</span></span>
<span id="cb22-12"><a href=""></a><span class="cf">if</span> <span class="op">(</span><span class="kw">static_cast</span><span class="op">&lt;</span><span class="dt">double</span><span class="op">&gt;(</span>a<span class="op">)</span> <span class="op">&lt;</span> b<span class="op">)</span> <span class="op">{</span></span>
<span id="cb22-13"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"a is smaller</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb22-14"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Appendix Slide 3 -->
</section>
<section id="practice-problems-4" class="slide level2">
<h2>Practice Problems</h2>
<ol type="1">
<li>Predict the output: <code>int a = 9, b = 4; cout &lt;&lt; a / b;</code> — then fix it to produce 2.25.</li>
<li>Rewrite a C-style cast <code>(int)3.7</code> using <code>static_cast&lt;&gt;</code>.</li>
<li>Write a program that reads an integer and prints the corresponding ASCII character.</li>
<li>What is the difference between <code>7 / 2.0</code> and <code>7 / 2</code>? When would each be the right choice?</li>
</ol>
<!-- Appendix Slide 4 -->
</section>
<section id="ai-search-terms-4" class="slide level2">
<h2>AI Search Terms</h2>
<ul>
<li>“C++ static_cast numeric conversion”</li>
<li>“C++ implicit type promotion”</li>
<li>“C++ narrowing conversion warning”</li>
<li>“C++ integer division truncation”</li>
<li>“C-style cast vs static_cast”</li>
</ul>
<!-- Appendix Slide 5 -->
</section>
<section id="questions-for-reflection-4" class="slide level2">
<h2>Questions for Reflection</h2>
<ul>
<li>Why does C++ keep both implicit and explicit conversion instead of requiring everything to be explicit?</li>
<li>When you divide two integers and expect a decimal result, which operand should you cast and why?</li>
<li>What risks do silent narrowing conversions introduce in a large program with many contributors?</li>
</ul>
<!-- Appendix Slide 6 -->
</section></section>
<section>
<section id="whats-the-output-type-casting" class="title-slide slide level1 center">
<h1>What’s the Output? — Type Casting</h1>

</section>
<section id="whats-the-output-type-casting-1" class="slide level2">
<h2>What’s the Output? — Type Casting</h2>
<p>Predicting output forces you to think through what the compiler actually does with types. Type casting is where many predictions fail — integer division, implicit promotion, and explicit casts all follow precise rules. Getting a prediction wrong here is useful: it identifies exactly which rule you had wrong.</p>
<aside class="notes">
<p>Total slides: 12</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 1 -->
</section>
<section id="how-to-use-these-exercises-1" class="slide level2">
<h2>How to Use These Exercises</h2>
<p>Read the code, predict the output, then advance. If your prediction was wrong, the explanation on the answer slide tells you which rule to revisit. Do not skip ahead.</p>
<!-- Slide 2 -->
</section>
<section id="whats-the-output-integer-division" class="slide level2">
<h2>What’s the Output? — Integer Division</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb23-1"><a href=""></a><span class="dt">int</span> a <span class="op">=</span> <span class="dv">7</span><span class="op">,</span> b <span class="op">=</span> <span class="dv">2</span><span class="op">;</span></span>
<span id="cb23-2"><a href=""></a>cout <span class="op">&lt;&lt;</span> a <span class="op">/</span> b<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Answer: 3</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 3 -->
</section>
<section id="output-integer-division" class="slide level2">
<h2>Output — Integer Division</h2>
<pre><code>3</code></pre>
<p>Both operands are <code>int</code>, so the result is <code>int</code>. The decimal part is discarded — not rounded. <code>7 / 2 = 3.5</code>, but integer division gives <code>3</code>. To get <code>3.5</code>, at least one operand must be a floating-point type.</p>
<aside class="notes">
<p>This is the most common “gotcha” early on. Reinforce: int / int = int, always.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 4 -->
</section>
<section id="whats-the-output-mixed-arithmetic" class="slide level2">
<h2>What’s the Output? — Mixed Arithmetic</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb25-1"><a href=""></a><span class="dt">int</span> a <span class="op">=</span> <span class="dv">7</span><span class="op">;</span></span>
<span id="cb25-2"><a href=""></a><span class="dt">double</span> b <span class="op">=</span> <span class="fl">2.0</span><span class="op">;</span></span>
<span id="cb25-3"><a href=""></a>cout <span class="op">&lt;&lt;</span> a <span class="op">/</span> b<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Answer: 3.5</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 5 -->
</section>
<section id="output-mixed-arithmetic" class="slide level2">
<h2>Output — Mixed Arithmetic</h2>
<pre><code>3.5</code></pre>
<p>When one operand is <code>double</code>, the <code>int</code> is implicitly promoted to <code>double</code> before the division is performed. <code>7.0 / 2.0 = 3.5</code>. One floating-point operand changes the entire expression’s type.</p>
<aside class="notes">
<p>Contrast with exercise 1. Emphasize: the presence of double forces promotion. This is implicit conversion in action.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 6 -->
</section>
<section id="whats-the-output-static_cast-narrowing" class="slide level2">
<h2>What’s the Output? — static_cast Narrowing</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb27-1"><a href=""></a><span class="dt">double</span> d <span class="op">=</span> <span class="fl">9.99</span><span class="op">;</span></span>
<span id="cb27-2"><a href=""></a><span class="dt">int</span> i <span class="op">=</span> <span class="kw">static_cast</span><span class="op">&lt;</span><span class="dt">int</span><span class="op">&gt;(</span>d<span class="op">);</span></span>
<span id="cb27-3"><a href=""></a>cout <span class="op">&lt;&lt;</span> i<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Answer: 9</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 7 -->
</section>
<section id="output-static_cast-narrowing" class="slide level2">
<h2>Output — static_cast Narrowing</h2>
<pre><code>9</code></pre>
<p><code>static_cast&lt;int&gt;()</code> truncates the decimal part — it does not round. <code>9.99</code> becomes <code>9</code>. The programmer explicitly requested this conversion, so the compiler performs it without a warning.</p>
<aside class="notes">
<p>Emphasize: truncation, not rounding. 9.99 → 9, not 10. This trips students up. Also note: the explicit cast means the programmer is accepting responsibility for the data loss.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 8 -->
</section>
<section id="whats-the-output-character-to-integer" class="slide level2">
<h2>What’s the Output? — Character to Integer</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb29-1"><a href=""></a><span class="dt">char</span> c <span class="op">=</span> <span class="ch">'A'</span><span class="op">;</span></span>
<span id="cb29-2"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="op">(</span><span class="dt">int</span><span class="op">)</span>c<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<aside class="notes">
<p>Answer: 65</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 9 -->
</section>
<section id="output-character-to-integer" class="slide level2">
<h2>Output — Character to Integer</h2>
<pre><code>65</code></pre>
<p><code>char</code> is a small integer type. <code>'A'</code> is stored as its ASCII value, 65. The C-style cast <code>(int)</code> reveals that underlying number. Modern C++ prefers <code>static_cast&lt;int&gt;(c)</code> over the C-style cast, but both produce the same result here.</p>
<aside class="notes">
<p>Many students are surprised that char is numeric. Reinforce: every character is stored as a number. The ASCII table defines which number maps to which character.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 10 -->
</section>
<section id="patterns-to-remember" class="slide level2">
<h2>Patterns to Remember</h2>
<ul>
<li><code>int / int</code> → <code>int</code> (decimal dropped)</li>
<li><code>int / double</code> → <code>double</code> (int is promoted first)</li>
<li><code>static_cast&lt;int&gt;(double)</code> → truncates toward zero, does not round</li>
<li><code>char</code> stores an integer; casting reveals its numeric value</li>
</ul>
<!-- Slide 11 -->
</section>
<section id="summary-5" class="slide level2">
<h2>Summary</h2>
<p>Integer division discards the decimal. Mixed arithmetic promotes the smaller type. Explicit casts truncate, not round. Every <code>char</code> has a numeric value. These four rules explain the output of most type-casting exercises you will encounter.</p>
<!-- Slide 12 -->
</section>
<section id="appendix-5" class="slide level2">
<h2>Appendix</h2>
<!-- Appendix -->
</section>
<section id="common-practices-5" class="slide level2">
<h2>Common Practices</h2>
<ul>
<li>Cast one operand to <code>double</code> before dividing when you need a decimal result.</li>
<li>Use <code>static_cast&lt;&gt;</code> instead of C-style casts in new code — it communicates intent and is searchable.</li>
<li>When converting <code>double</code> to <code>int</code>, decide whether truncation is correct or whether rounding is needed (<code>round()</code> from <code>&lt;cmath&gt;</code>).</li>
</ul>
<!-- Appendix Slide 1 -->
</section>
<section id="common-mistakes-5" class="slide level2">
<h2>Common Mistakes</h2>
<ul>
<li>Expecting <code>7 / 2</code> to produce <code>3.5</code> — it produces <code>3</code>.</li>
<li>Assuming <code>static_cast&lt;int&gt;(9.9)</code> rounds to <code>10</code> — it truncates to <code>9</code>.</li>
<li>Using C-style casts on pointer types where <code>static_cast</code> would be rejected — C-style casts bypass safety checks.</li>
</ul>
<!-- Appendix Slide 2 -->
</section>
<section id="more-examples-5" class="slide level2">
<h2>More Examples</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb31"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb31-1"><a href=""></a><span class="co">// Rounding vs truncation</span></span>
<span id="cb31-2"><a href=""></a><span class="dt">double</span> x <span class="op">=</span> <span class="fl">4.7</span><span class="op">;</span></span>
<span id="cb31-3"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">static_cast</span><span class="op">&lt;</span><span class="dt">int</span><span class="op">&gt;(</span>x<span class="op">);</span>          <span class="co">// 4 (truncated)</span></span>
<span id="cb31-4"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">static_cast</span><span class="op">&lt;</span><span class="dt">int</span><span class="op">&gt;(</span>round<span class="op">(</span>x<span class="op">));</span>   <span class="co">// 5 (rounded)</span></span>
<span id="cb31-5"><a href=""></a></span>
<span id="cb31-6"><a href=""></a><span class="co">// char arithmetic</span></span>
<span id="cb31-7"><a href=""></a><span class="dt">char</span> c <span class="op">=</span> <span class="ch">'a'</span><span class="op">;</span></span>
<span id="cb31-8"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">static_cast</span><span class="op">&lt;</span><span class="dt">int</span><span class="op">&gt;(</span>c <span class="op">+</span> <span class="dv">1</span><span class="op">);</span>      <span class="co">// 98 (ASCII for 'b')</span></span>
<span id="cb31-9"><a href=""></a></span>
<span id="cb31-10"><a href=""></a><span class="co">// Division with explicit cast</span></span>
<span id="cb31-11"><a href=""></a><span class="dt">int</span> p <span class="op">=</span> <span class="dv">10</span><span class="op">,</span> q <span class="op">=</span> <span class="dv">3</span><span class="op">;</span></span>
<span id="cb31-12"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">static_cast</span><span class="op">&lt;</span><span class="dt">double</span><span class="op">&gt;(</span>p<span class="op">)</span> <span class="op">/</span> q<span class="op">;</span>   <span class="co">// 3.3333...</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Appendix Slide 3 -->
</section>
<section id="practice-problems-5" class="slide level2">
<h2>Practice Problems</h2>
<ol type="1">
<li>Predict: <code>cout &lt;&lt; 5 / 2;</code> then <code>cout &lt;&lt; 5 / 2.0;</code> — what are the two outputs and why?</li>
<li>What does <code>static_cast&lt;int&gt;(-3.9)</code> produce? Truncation rounds toward zero — does that mean it produces <code>-3</code> or <code>-4</code>?</li>
<li>Write one line that prints the ASCII value of the character <code>'z'</code>.</li>
<li>Predict: <code>int a = 3; double b = 1.5; cout &lt;&lt; a * b;</code></li>
</ol>
<!-- Appendix Slide 4 -->
</section>
<section id="ai-search-terms-5" class="slide level2">
<h2>AI Search Terms</h2>
<ul>
<li>“C++ integer division truncation”</li>
<li>“C++ implicit type promotion arithmetic”</li>
<li>“C++ static_cast truncation vs rounding”</li>
<li>“C++ char ASCII numeric value”</li>
<li>“C++ mixed type arithmetic rules”</li>
</ul>
<!-- Appendix Slide 5 -->
</section>
<section id="questions-for-reflection-5" class="slide level2">
<h2>Questions for Reflection</h2>
<ul>
<li>Why does C++ perform integer division rather than automatically promoting to floating-point?</li>
<li>When would truncation be the correct behavior, and when would you need explicit rounding instead?</li>
<li>What does the presence of <code>static_cast</code> in code signal to a code reviewer?</li>
</ul>
<!-- Appendix Slide 6 -->
</section></section>
<section>
<section id="signed-vs-unsigned-variables" class="title-slide slide level1 center">
<h1>Signed vs Unsigned Variables</h1>

</section>
<section id="signed-vs-unsigned-variables-1" class="slide level2">
<h2>Signed vs Unsigned Variables</h2>
<p>How does a variable store negative numbers, and when should you choose signed over unsigned? The difference is not just range — it affects overflow behavior, comparison logic, and compatibility with standard library types. Most of these bugs appear silently.</p>
<aside class="notes">
<p>Total slides: 9</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 1 -->
</section>
<section id="signed-how-negatives-are-stored" class="slide level2">
<h2>Signed: How Negatives Are Stored</h2>
<p>A signed integer uses the most significant bit (MSB) as a sign bit. In two’s complement — the format used on all modern hardware — a 1 in the MSB means negative, 0 means non-negative. A 32-bit signed <code>int</code> uses 31 bits for magnitude and 1 bit for the sign.</p>
<aside class="notes">
<p>[Graphic suggestion: 32-bit layout showing bit 31 as the sign bit and bits 0–30 as the value bits.]</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 2 -->
</section>
<section id="unsigned-all-bits-for-magnitude" class="slide level2">
<h2>Unsigned: All Bits for Magnitude</h2>
<p>An unsigned variable has no sign bit — all bits represent magnitude. A 32-bit <code>unsigned int</code> uses all 32 bits, doubling the positive range compared to a signed <code>int</code>.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Type</th>
<th>Minimum</th>
<th>Maximum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>int</code> (signed)</td>
<td>−2,147,483,648</td>
<td>2,147,483,647</td>
</tr>
<tr class="even">
<td><code>unsigned int</code></td>
<td>0</td>
<td>4,294,967,295</td>
</tr>
<tr class="odd">
<td><code>short</code> (signed)</td>
<td>−32,768</td>
<td>32,767</td>
</tr>
<tr class="even">
<td><code>unsigned short</code></td>
<td>0</td>
<td>65,535</td>
</tr>
</tbody>
</table>
<!-- Slide 3 -->
</section>
<section id="when-to-use-unsigned" class="slide level2">
<h2>When to Use Unsigned</h2>
<p>Use unsigned when:</p>
<ul>
<li>The value can never be negative (sizes, counts, array indices)</li>
<li>Performing bit manipulation (flags, masks, bitwise operations)</li>
<li>Matching the type returned by <code>.size()</code> on containers — it returns <code>size_t</code>, which is unsigned</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb32-1"><a href=""></a><span class="cf">for</span> <span class="op">(</span><span class="dt">size_t</span> i <span class="op">=</span> <span class="dv">0</span><span class="op">;</span> i <span class="op">&lt;</span> vec<span class="op">.</span>size<span class="op">();</span> <span class="op">++</span>i<span class="op">)</span> <span class="op">{</span></span>
<span id="cb32-2"><a href=""></a>    <span class="co">// size_t is unsigned; matches vec.size() type exactly</span></span>
<span id="cb32-3"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Slide 4 -->
</section>
<section id="when-to-use-signed" class="slide level2">
<h2>When to Use Signed</h2>
<p>Use signed for all general arithmetic unless there is a specific reason for unsigned. Signed is the default for <code>int</code>, <code>short</code>, and <code>long</code>. If a variable can ever be negative — even theoretically — use signed.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb33-1"><a href=""></a><span class="dt">int</span> temperature <span class="op">=</span> <span class="op">-</span><span class="dv">15</span><span class="op">;</span>    <span class="co">// can be negative</span></span>
<span id="cb33-2"><a href=""></a><span class="dt">int</span> balance     <span class="op">=</span> <span class="op">-</span><span class="dv">200</span><span class="op">;</span>   <span class="co">// account overdraft</span></span>
<span id="cb33-3"><a href=""></a><span class="dt">int</span> velocity    <span class="op">=</span> <span class="op">-</span><span class="dv">50</span><span class="op">;</span>    <span class="co">// moving in reverse</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Slide 5 -->
</section>
<section id="mixing-signed-and-unsigned-the-trap" class="slide level2">
<h2>Mixing Signed and Unsigned: The Trap</h2>
<p>When a signed and unsigned value are compared or combined in an expression, the signed value is implicitly converted to unsigned. A negative signed value becomes a very large positive unsigned value.</p>
<!-- Slide 6 -->
</section>
<section id="mixing-signed-and-unsigned-code" class="slide level2">
<h2>Mixing Signed and Unsigned — Code</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb34-1"><a href=""></a><span class="dt">int</span>   s <span class="op">=</span>  <span class="op">-</span><span class="dv">5</span><span class="op">;</span></span>
<span id="cb34-2"><a href=""></a><span class="dt">unsigned</span> <span class="dt">int</span> u <span class="op">=</span> <span class="dv">10</span><span class="op">;</span></span>
<span id="cb34-3"><a href=""></a></span>
<span id="cb34-4"><a href=""></a><span class="cf">if</span> <span class="op">(</span>s <span class="op">&lt;</span> u<span class="op">)</span> <span class="op">{</span></span>
<span id="cb34-5"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"s &lt; u</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span>   <span class="co">// Looks like it should print...</span></span>
<span id="cb34-6"><a href=""></a><span class="op">}</span> <span class="cf">else</span> <span class="op">{</span></span>
<span id="cb34-7"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"NOT s &lt; u</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span>  <span class="co">// ...but this prints instead</span></span>
<span id="cb34-8"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>-5</code> is converted to <code>unsigned int</code>: it becomes 4,294,967,291. The comparison <code>4294967291 &lt; 10</code> is false. Enable <code>-Wsign-compare</code> to catch this at compile time.</p>
<aside class="notes">
<p>This is a real source of security bugs in C++ — bounds checks that silently invert.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 7 -->
</section>
<section id="overflow-behavior-differs" class="slide level2">
<h2>Overflow Behavior Differs</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb35-1"><a href=""></a><span class="dt">int</span> s <span class="op">=</span> INT_MAX<span class="op">;</span></span>
<span id="cb35-2"><a href=""></a>s<span class="op">++;</span>              <span class="co">// Undefined behavior — do not rely on this</span></span>
<span id="cb35-3"><a href=""></a></span>
<span id="cb35-4"><a href=""></a><span class="dt">unsigned</span> <span class="dt">int</span> u <span class="op">=</span> UINT_MAX<span class="op">;</span></span>
<span id="cb35-5"><a href=""></a>u<span class="op">++;</span>              <span class="co">// Well-defined: wraps to 0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Signed overflow is undefined. Unsigned overflow is defined modular arithmetic. This is one of the few places where the two types behave fundamentally differently at the language level.</p>
<!-- Slide 8 -->
</section>
<section id="summary-6" class="slide level2">
<h2>Summary</h2>
<p>Signed is the safe default for general arithmetic; unsigned is appropriate for sizes, indices, and bit operations. Mixing the two in comparisons or arithmetic silently converts signed to unsigned — a common source of logic bugs. Enable sign-comparison warnings and address them rather than casting them away.</p>
<!-- Slide 9 -->
</section>
<section id="appendix-6" class="slide level2">
<h2>Appendix</h2>
<!-- Appendix -->
</section>
<section id="common-practices-6" class="slide level2">
<h2>Common Practices</h2>
<ul>
<li>Default to <code>int</code> for general arithmetic; switch to unsigned only when the domain guarantees non-negative values.</li>
<li>Use <code>size_t</code> for container indices and loop counters over containers — it matches <code>.size()</code> and avoids sign-comparison warnings.</li>
<li>Enable <code>-Wsign-compare</code> (or equivalent) in your compiler settings and treat the warnings as errors.</li>
</ul>
<!-- Appendix Slide 1 -->
</section>
<section id="common-mistakes-6" class="slide level2">
<h2>Common Mistakes</h2>
<ul>
<li>Comparing <code>int</code> to the result of <code>.size()</code> — <code>.size()</code> returns <code>size_t</code> (unsigned), and a negative <code>int</code> silently becomes a huge positive value.</li>
<li>Decrementing an unsigned counter past zero in a loop — the loop never terminates because the underflow wraps to a large positive value.</li>
<li>Assuming signed and unsigned overflow behave the same way — they follow different rules with different consequences.</li>
</ul>
<!-- Appendix Slide 2 -->
</section>
<section id="more-examples-6" class="slide level2">
<h2>More Examples</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb36-1"><a href=""></a><span class="co">// Infinite loop due to unsigned underflow</span></span>
<span id="cb36-2"><a href=""></a><span class="cf">for</span> <span class="op">(</span><span class="dt">unsigned</span> <span class="dt">int</span> i <span class="op">=</span> <span class="dv">10</span><span class="op">;</span> i <span class="op">&gt;=</span> <span class="dv">0</span><span class="op">;</span> i<span class="op">--)</span> <span class="op">{</span></span>
<span id="cb36-3"><a href=""></a>    cout <span class="op">&lt;&lt;</span> i <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span>  <span class="co">// When i is 0, i-- wraps to UINT_MAX</span></span>
<span id="cb36-4"><a href=""></a><span class="op">}</span></span>
<span id="cb36-5"><a href=""></a></span>
<span id="cb36-6"><a href=""></a><span class="co">// Safe: use signed int instead</span></span>
<span id="cb36-7"><a href=""></a><span class="cf">for</span> <span class="op">(</span><span class="dt">int</span> i <span class="op">=</span> <span class="dv">10</span><span class="op">;</span> i <span class="op">&gt;=</span> <span class="dv">0</span><span class="op">;</span> i<span class="op">--)</span> <span class="op">{</span></span>
<span id="cb36-8"><a href=""></a>    cout <span class="op">&lt;&lt;</span> i <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span>  <span class="co">// Terminates correctly</span></span>
<span id="cb36-9"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Appendix Slide 3 -->
</section>
<section id="practice-problems-6" class="slide level2">
<h2>Practice Problems</h2>
<ol type="1">
<li>Predict the output: <code>int x = -1; unsigned int y = 1; cout &lt;&lt; (x &lt; y);</code> — and explain why.</li>
<li>Rewrite this loop correctly: <code>for (int i = 0; i &lt; vec.size(); ++i) {}</code></li>
<li>What is the minimum and maximum value of <code>unsigned short</code>? Verify with <code>numeric_limits</code>.</li>
<li>Write a loop that counts down from 5 to 0 using <code>unsigned int</code>. What change prevents an infinite loop?</li>
</ol>
<!-- Appendix Slide 4 -->
</section>
<section id="ai-search-terms-6" class="slide level2">
<h2>AI Search Terms</h2>
<ul>
<li>“C++ signed vs unsigned integer”</li>
<li>“C++ sign-compare warning Wsign-compare”</li>
<li>“C++ size_t container loop”</li>
<li>“C++ unsigned integer underflow wraparound”</li>
<li>“two’s complement signed representation”</li>
</ul>
<!-- Appendix Slide 5 -->
</section>
<section id="questions-for-reflection-6" class="slide level2">
<h2>Questions for Reflection</h2>
<ul>
<li>Why does C++ default to signed integers rather than unsigned?</li>
<li>How would you design a function parameter to make clear that negative values are not accepted?</li>
<li>What category of real-world bug is most commonly caused by sign/unsigned mismatches?</li>
</ul>
<!-- Appendix Slide 6 -->
</section></section>
<section>
<section id="fixed-width-integers-and-size_t" class="title-slide slide level1 center">
<h1>Fixed Width Integers and size_t</h1>

</section>
<section id="fixed-width-integers-and-size_t-1" class="slide level2">
<h2>Fixed Width Integers and size_t</h2>
<p>If <code>int</code> is 4 bytes on one system and 2 bytes on another, how do you write code that behaves identically everywhere? C++ provides fixed-width integer types that guarantee an exact size regardless of platform. This section also introduces <code>size_t</code>, the standard type for anything that measures a size in memory.</p>
<aside class="notes">
<p>Total slides: 9</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 1 -->
</section>
<section id="the-problem-platform-dependent-sizes" class="slide level2">
<h2>The Problem: Platform-Dependent Sizes</h2>
<p>The standard types <code>int</code>, <code>short</code>, and <code>long</code> have minimum guaranteed sizes but no maximum. In practice, <code>int</code> is 4 bytes on most modern systems, but embedded and legacy platforms differ. Code that assumes a fixed size silently breaks when compiled elsewhere.</p>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 2 -->
</section>
<section id="fixed-width-types-from-cstdint" class="slide level2">
<h2>Fixed-Width Types from <code>&lt;cstdint&gt;</code></h2>
<p><code>&lt;cstdint&gt;</code> provides types with guaranteed sizes:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Type</th>
<th>Signed</th>
<th>Unsigned</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>8-bit</td>
<td><code>int8_t</code></td>
<td><code>uint8_t</code></td>
</tr>
<tr class="even">
<td>16-bit</td>
<td><code>int16_t</code></td>
<td><code>uint16_t</code></td>
</tr>
<tr class="odd">
<td>32-bit</td>
<td><code>int32_t</code></td>
<td><code>uint32_t</code></td>
</tr>
<tr class="even">
<td>64-bit</td>
<td><code>int64_t</code></td>
<td><code>uint64_t</code></td>
</tr>
</tbody>
</table>
<p>If the platform cannot provide that exact size, the type does not exist — you get a compile error rather than silent data corruption.</p>
<!-- Slide 3 -->
</section>
<section id="using-fixed-width-types" class="slide level2">
<h2>Using Fixed-Width Types</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb37-1"><a href=""></a><span class="pp">#include </span><span class="im">&lt;cstdint&gt;</span></span>
<span id="cb37-2"><a href=""></a><span class="pp">#include </span><span class="im">&lt;iostream&gt;</span></span>
<span id="cb37-3"><a href=""></a><span class="kw">using</span> <span class="kw">namespace</span> std<span class="op">;</span></span>
<span id="cb37-4"><a href=""></a></span>
<span id="cb37-5"><a href=""></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb37-6"><a href=""></a>    <span class="dt">int32_t</span>  count   <span class="op">=</span> <span class="dv">2000000000</span><span class="op">;</span>   <span class="co">// guaranteed 32-bit signed</span></span>
<span id="cb37-7"><a href=""></a>    <span class="dt">uint8_t</span>  flags   <span class="op">=</span> <span class="bn">0b10101010</span><span class="op">;</span>   <span class="co">// guaranteed 8-bit unsigned</span></span>
<span id="cb37-8"><a href=""></a>    <span class="dt">int64_t</span>  balance <span class="op">=</span> <span class="op">-</span><span class="dv">900000000000</span><span class="bu">LL</span><span class="op">;</span></span>
<span id="cb37-9"><a href=""></a></span>
<span id="cb37-10"><a href=""></a>    cout <span class="op">&lt;&lt;</span> count   <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb37-11"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="op">(</span><span class="dt">int</span><span class="op">)</span>flags <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb37-12"><a href=""></a>    cout <span class="op">&lt;&lt;</span> balance <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb37-13"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Slide 4 -->
</section>
<section id="when-to-use-fixed-width-types" class="slide level2">
<h2>When to Use Fixed-Width Types</h2>
<p>Use fixed-width types when:</p>
<ul>
<li>The exact bit width matters: network protocols, binary file formats, hardware registers</li>
<li>Code must be portable across platforms with different word sizes</li>
<li>You need bit manipulation with a known field width</li>
</ul>
<p>Do not use them for general arithmetic where the exact size does not matter — the standard <code>int</code> and <code>long</code> are fine there.</p>
<!-- Slide 5 -->
</section>
<section id="what-is-size_t" class="slide level2">
<h2>What Is size_t?</h2>
<p><code>size_t</code> is the unsigned integer type returned by <code>sizeof()</code> and by <code>.size()</code> on any container. It is guaranteed to be large enough to represent the size of any object in memory on the current platform — typically 4 bytes on 32-bit systems and 8 bytes on 64-bit systems.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb38-1"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span><span class="dt">int</span><span class="op">)</span>   <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span>  <span class="co">// returns size_t</span></span>
<span id="cb38-2"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span><span class="dt">double</span><span class="op">)</span> <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb38-3"><a href=""></a></span>
<span id="cb38-4"><a href=""></a>vector<span class="op">&lt;</span><span class="dt">int</span><span class="op">&gt;</span> v <span class="op">=</span> <span class="op">{</span><span class="dv">1</span><span class="op">,</span> <span class="dv">2</span><span class="op">,</span> <span class="dv">3</span><span class="op">};</span></span>
<span id="cb38-5"><a href=""></a>cout <span class="op">&lt;&lt;</span> v<span class="op">.</span>size<span class="op">()</span> <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span>       <span class="co">// also returns size_t</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Slide 6 -->
</section>
<section id="using-size_t-for-loop-indices" class="slide level2">
<h2>Using size_t for Loop Indices</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb39-1"><a href=""></a>vector<span class="op">&lt;</span>string<span class="op">&gt;</span> names <span class="op">=</span> <span class="op">{</span><span class="st">"Alice"</span><span class="op">,</span> <span class="st">"Bob"</span><span class="op">,</span> <span class="st">"Carol"</span><span class="op">};</span></span>
<span id="cb39-2"><a href=""></a></span>
<span id="cb39-3"><a href=""></a><span class="cf">for</span> <span class="op">(</span><span class="dt">size_t</span> i <span class="op">=</span> <span class="dv">0</span><span class="op">;</span> i <span class="op">&lt;</span> names<span class="op">.</span>size<span class="op">();</span> <span class="op">++</span>i<span class="op">)</span> <span class="op">{</span></span>
<span id="cb39-4"><a href=""></a>    cout <span class="op">&lt;&lt;</span> names<span class="op">[</span>i<span class="op">]</span> <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb39-5"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Comparing <code>int</code> to <code>size_t</code> triggers a sign-comparison warning. Using <code>size_t</code> for the loop counter eliminates the warning and is semantically correct — an index into a container cannot be negative.</p>
<aside class="notes">

<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 7 -->
</section>
<section id="fast-and-least-variants-brief" class="slide level2">
<h2>Fast and Least Variants (Brief)</h2>
<p><code>&lt;cstdint&gt;</code> also defines:</p>
<ul>
<li><code>int_fast32_t</code> — at least 32 bits; the fastest available type of that width on the platform</li>
<li><code>int_least8_t</code> — the smallest type with at least 8 bits</li>
</ul>
<p>These exist for performance-sensitive code. At the introductory level, use the exact-width types (<code>int32_t</code>) unless you have a specific reason to choose otherwise.</p>
<!-- Slide 8 -->
</section>
<section id="summary-7" class="slide level2">
<h2>Summary</h2>
<p>Fixed-width integer types guarantee an exact size on any platform. Use them when bit width matters — protocols, file formats, hardware. Use <code>size_t</code> for sizes, indices, and anything that measures memory or container length. For everything else, <code>int</code> is fine.</p>
<!-- Slide 9 -->
</section>
<section id="appendix-7" class="slide level2">
<h2>Appendix</h2>
<!-- Appendix -->
</section>
<section id="common-practices-7" class="slide level2">
<h2>Common Practices</h2>
<ul>
<li>Include <code>&lt;cstdint&gt;</code> whenever you use fixed-width types.</li>
<li>Use <code>size_t</code> for loop indices over containers to avoid sign-comparison warnings.</li>
<li>Choose <code>int32_t</code> over <code>int</code> when you are writing cross-platform code that assumes a specific range.</li>
<li>Never hardcode sizes like <code>4</code> for <code>int</code> — use <code>sizeof()</code> or the appropriate <code>size_t</code> instead.</li>
</ul>
<!-- Appendix Slide 1 -->
</section>
<section id="common-mistakes-7" class="slide level2">
<h2>Common Mistakes</h2>
<ul>
<li>Using <code>int8_t</code> for small numbers and then printing it directly — it may print as a character since <code>int8_t</code> is often <code>signed char</code>.</li>
<li>Assuming <code>size_t</code> is always 64 bits — it is platform-dependent (32 bits on 32-bit systems).</li>
<li>Mixing <code>int</code> and <code>size_t</code> in comparisons without a cast — the signed <code>int</code> is silently converted to unsigned.</li>
</ul>
<!-- Appendix Slide 2 -->
</section>
<section id="more-examples-7" class="slide level2">
<h2>More Examples</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb40-1"><a href=""></a><span class="pp">#include </span><span class="im">&lt;cstdint&gt;</span></span>
<span id="cb40-2"><a href=""></a><span class="pp">#include </span><span class="im">&lt;iostream&gt;</span></span>
<span id="cb40-3"><a href=""></a><span class="kw">using</span> <span class="kw">namespace</span> std<span class="op">;</span></span>
<span id="cb40-4"><a href=""></a></span>
<span id="cb40-5"><a href=""></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb40-6"><a href=""></a>    <span class="dt">uint32_t</span> pixel <span class="op">=</span> <span class="bn">0xFF8800FF</span><span class="op">;</span>    <span class="co">// RGBA color packed in 32 bits</span></span>
<span id="cb40-7"><a href=""></a>    <span class="dt">uint8_t</span>  r <span class="op">=</span> <span class="op">(</span>pixel <span class="op">&gt;&gt;</span> <span class="dv">24</span><span class="op">)</span> <span class="op">&amp;</span> <span class="bn">0xFF</span><span class="op">;</span></span>
<span id="cb40-8"><a href=""></a>    <span class="dt">uint8_t</span>  g <span class="op">=</span> <span class="op">(</span>pixel <span class="op">&gt;&gt;</span> <span class="dv">16</span><span class="op">)</span> <span class="op">&amp;</span> <span class="bn">0xFF</span><span class="op">;</span></span>
<span id="cb40-9"><a href=""></a>    <span class="dt">uint8_t</span>  b <span class="op">=</span> <span class="op">(</span>pixel <span class="op">&gt;&gt;</span> <span class="dv">8</span><span class="op">)</span>  <span class="op">&amp;</span> <span class="bn">0xFF</span><span class="op">;</span></span>
<span id="cb40-10"><a href=""></a></span>
<span id="cb40-11"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"R: "</span> <span class="op">&lt;&lt;</span> <span class="op">(</span><span class="dt">int</span><span class="op">)</span>r <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span>  <span class="co">// 255</span></span>
<span id="cb40-12"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"G: "</span> <span class="op">&lt;&lt;</span> <span class="op">(</span><span class="dt">int</span><span class="op">)</span>g <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span>  <span class="co">// 136</span></span>
<span id="cb40-13"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"B: "</span> <span class="op">&lt;&lt;</span> <span class="op">(</span><span class="dt">int</span><span class="op">)</span>b <span class="op">&lt;&lt;</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span>  <span class="co">// 0</span></span>
<span id="cb40-14"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Packing and unpacking data into exact-width fields is one of the primary use cases for fixed-width types.</p>
<!-- Appendix Slide 3 -->
</section>
<section id="practice-problems-7" class="slide level2">
<h2>Practice Problems</h2>
<ol type="1">
<li>Write a program that prints <code>sizeof</code> for <code>int8_t</code>, <code>int16_t</code>, <code>int32_t</code>, and <code>int64_t</code>.</li>
<li>Rewrite a loop that uses <code>int i</code> to iterate over a <code>vector&lt;string&gt;</code> using <code>size_t</code> instead.</li>
<li>What is the maximum value of <code>uint16_t</code>? Calculate it as 2^16 − 1 and verify with <code>numeric_limits</code>.</li>
<li>When would you choose <code>int_fast32_t</code> over <code>int32_t</code>?</li>
</ol>
<!-- Appendix Slide 4 -->
</section>
<section id="ai-search-terms-7" class="slide level2">
<h2>AI Search Terms</h2>
<ul>
<li>“C++ fixed width integer types cstdint”</li>
<li>“C++ int32_t uint64_t portable types”</li>
<li>“C++ size_t vs int loop index”</li>
<li>“C++ int_fast32_t int_least8_t”</li>
<li>“C++ cross-platform integer types”</li>
</ul>
<!-- Appendix Slide 5 -->
</section>
<section id="questions-for-reflection-7" class="slide level2">
<h2>Questions for Reflection</h2>
<ul>
<li>Why does the C++ standard allow <code>int</code> to have different sizes instead of mandating 32 bits?</li>
<li>What could go wrong if you read a binary file format using <code>int</code> on a 32-bit and then a 64-bit system?</li>
<li>Why does <code>size_t</code> need to be unsigned rather than signed?</li>
</ul>
<!-- Appendix Slide 6 -->
</section></section>
<section>
<section id="determining-variable-size" class="title-slide slide level1 center">
<h1>Determining Variable Size</h1>

</section>
<section id="determining-variable-size-1" class="slide level2">
<h2>Determining Variable Size</h2>
<p>How can you programmatically find out how much memory a variable or type occupies? C++ provides the <code>sizeof</code> operator for exactly this purpose. It evaluates at compile time and works on any type, variable, or array — and it is the only portable way to measure memory.</p>
<aside class="notes">
<p>Total slides: 8</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 1 -->
</section>
<section id="the-sizeof-operator" class="slide level2">
<h2>The sizeof Operator</h2>
<p><code>sizeof</code> is a compile-time operator that returns the size of a type or variable in bytes. It does not execute code or evaluate the operand’s value — it determines size from type information alone. The return type is <code>size_t</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb41-1"><a href=""></a><span class="kw">sizeof</span><span class="op">(</span>type<span class="op">)</span>      <span class="co">// size of a type</span></span>
<span id="cb41-2"><a href=""></a><span class="kw">sizeof</span> variable   <span class="co">// size of a declared variable</span></span>
<span id="cb41-3"><a href=""></a><span class="kw">sizeof</span><span class="op">(</span>expr<span class="op">)</span>      <span class="co">// size of the type an expression would produce</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Slide 2 -->
</section>
<section id="typical-platform-sizes" class="slide level2">
<h2>Typical Platform Sizes</h2>
<p>Sizes are not mandated by the standard and vary by platform and compiler. These are typical on a 64-bit system with a modern C++ compiler:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Type</th>
<th>Typical Size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>char</code></td>
<td>1 byte</td>
</tr>
<tr class="even">
<td><code>short</code></td>
<td>2 bytes</td>
</tr>
<tr class="odd">
<td><code>int</code></td>
<td>4 bytes</td>
</tr>
<tr class="even">
<td><code>long</code></td>
<td>8 bytes</td>
</tr>
<tr class="odd">
<td><code>float</code></td>
<td>4 bytes</td>
</tr>
<tr class="even">
<td><code>double</code></td>
<td>8 bytes</td>
</tr>
<tr class="odd">
<td><code>bool</code></td>
<td>1 byte</td>
</tr>
<tr class="even">
<td>pointer</td>
<td>8 bytes</td>
</tr>
</tbody>
</table>
<p>Always use <code>sizeof</code> rather than assuming these values.</p>
<!-- Slide 3 -->
</section>
<section id="why-sizes-vary" class="slide level2">
<h2>Why Sizes Vary</h2>
<ul>
<li><strong>Architecture</strong>: 32-bit systems use 4-byte pointers; 64-bit systems use 8-byte pointers.</li>
<li><strong>Compiler choices</strong>: <code>long</code> is 4 bytes on Windows (MSVC) and 8 bytes on Linux (GCC/Clang).</li>
<li><strong>Alignment</strong>: the compiler inserts padding between struct members to align data on word boundaries for performance.</li>
</ul>
<!-- Slide 4 -->
</section>
<section id="sizeof-with-arrays" class="slide level2">
<h2>sizeof with Arrays</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb42"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb42-1"><a href=""></a><span class="dt">int</span> arr<span class="op">[</span><span class="dv">10</span><span class="op">];</span></span>
<span id="cb42-2"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span>arr<span class="op">);</span>              <span class="co">// 40  (10 * 4 bytes)</span></span>
<span id="cb42-3"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span>arr<span class="op">[</span><span class="dv">0</span><span class="op">]);</span>           <span class="co">// 4   (size of one int)</span></span>
<span id="cb42-4"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span>arr<span class="op">)</span> <span class="op">/</span> <span class="kw">sizeof</span><span class="op">(</span>arr<span class="op">[</span><span class="dv">0</span><span class="op">]);</span>  <span class="co">// 10  (element count)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The idiom <code>sizeof(arr) / sizeof(arr[0])</code> gives the number of elements in a statically allocated array. It does not work for pointer parameters — the array decays to a pointer and you get pointer size, not array size.</p>
<!-- Slide 5 -->
</section>
<section id="sizeof-with-structs-padding" class="slide level2">
<h2>sizeof with Structs: Padding</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb43-1"><a href=""></a><span class="kw">struct</span> Point <span class="op">{</span></span>
<span id="cb43-2"><a href=""></a>    <span class="dt">char</span> x<span class="op">;</span>   <span class="co">// 1 byte</span></span>
<span id="cb43-3"><a href=""></a>    <span class="co">// 3 bytes padding inserted by compiler</span></span>
<span id="cb43-4"><a href=""></a>    <span class="dt">int</span>  y<span class="op">;</span>   <span class="co">// 4 bytes</span></span>
<span id="cb43-5"><a href=""></a><span class="op">};</span></span>
<span id="cb43-6"><a href=""></a></span>
<span id="cb43-7"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span>Point<span class="op">);</span>  <span class="co">// 8 (not 5)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The compiler aligns <code>int</code> members on 4-byte boundaries. Padding is invisible in code but real in memory. Reordering members (largest first) can reduce total struct size.</p>
<aside class="notes">
<p>[Graphic suggestion: Memory layout diagram showing 1-byte x, 3-byte padding gap, 4-byte y.]</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- Slide 6 -->
</section>
<section id="printing-all-type-sizes" class="slide level2">
<h2>Printing All Type Sizes</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb44-1"><a href=""></a><span class="pp">#include </span><span class="im">&lt;iostream&gt;</span></span>
<span id="cb44-2"><a href=""></a><span class="kw">using</span> <span class="kw">namespace</span> std<span class="op">;</span></span>
<span id="cb44-3"><a href=""></a></span>
<span id="cb44-4"><a href=""></a><span class="dt">int</span> main<span class="op">()</span> <span class="op">{</span></span>
<span id="cb44-5"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"char:   "</span> <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span><span class="dt">char</span><span class="op">)</span>   <span class="op">&lt;&lt;</span> <span class="st">" byte(s)</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb44-6"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"short:  "</span> <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span><span class="dt">short</span><span class="op">)</span>  <span class="op">&lt;&lt;</span> <span class="st">" byte(s)</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb44-7"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"int:    "</span> <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span><span class="dt">int</span><span class="op">)</span>    <span class="op">&lt;&lt;</span> <span class="st">" byte(s)</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb44-8"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"long:   "</span> <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span><span class="dt">long</span><span class="op">)</span>   <span class="op">&lt;&lt;</span> <span class="st">" byte(s)</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb44-9"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"float:  "</span> <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span><span class="dt">float</span><span class="op">)</span>  <span class="op">&lt;&lt;</span> <span class="st">" byte(s)</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb44-10"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"double: "</span> <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span><span class="dt">double</span><span class="op">)</span> <span class="op">&lt;&lt;</span> <span class="st">" byte(s)</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb44-11"><a href=""></a>    cout <span class="op">&lt;&lt;</span> <span class="st">"bool:   "</span> <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span><span class="dt">bool</span><span class="op">)</span>   <span class="op">&lt;&lt;</span> <span class="st">" byte(s)</span><span class="sc">\n</span><span class="st">"</span><span class="op">;</span></span>
<span id="cb44-12"><a href=""></a><span class="op">}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Run this on your machine. The output is specific to your compiler and platform.</p>
<!-- Slide 7 -->
</section>
<section id="summary-8" class="slide level2">
<h2>Summary</h2>
<p><code>sizeof</code> is the portable, compile-time way to determine memory size. Use it instead of hardcoding byte counts. Remember that struct size includes alignment padding — the total is not always the sum of member sizes.</p>
<!-- Slide 8 -->
</section>
<section id="appendix-8" class="slide level2">
<h2>Appendix</h2>
<!-- Appendix -->
</section>
<section id="common-practices-8" class="slide level2">
<h2>Common Practices</h2>
<ul>
<li>Always use <code>sizeof</code> rather than hardcoding byte sizes — platforms differ.</li>
<li>Use <code>sizeof(arr) / sizeof(arr[0])</code> to count elements in a statically allocated array.</li>
<li>When designing structs for memory efficiency, order members from largest to smallest to minimize padding.</li>
<li>Store <code>sizeof</code> results in a <code>size_t</code> variable if reused multiple times in a calculation.</li>
</ul>
<!-- Appendix Slide 1 -->
</section>
<section id="common-mistakes-8" class="slide level2">
<h2>Common Mistakes</h2>
<ul>
<li>Passing an array to a function and calling <code>sizeof</code> inside the function — the array has decayed to a pointer; you get the pointer size, not the array size.</li>
<li>Assuming <code>sizeof(struct)</code> equals the sum of its member sizes — padding almost always makes it larger.</li>
<li>Confusing <code>sizeof(vector&lt;int&gt;)</code> with the number of elements — it returns the size of the vector object itself, not its contents.</li>
</ul>
<!-- Appendix Slide 2 -->
</section>
<section id="more-examples-8" class="slide level2">
<h2>More Examples</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb45"><pre class="sourceCode numberSource cpp number-lines code-with-copy"><code class="sourceCode cpp"><span id="cb45-1"><a href=""></a><span class="co">// Pointer size is independent of pointed-to type</span></span>
<span id="cb45-2"><a href=""></a><span class="dt">char</span><span class="op">*</span> p1 <span class="op">=</span> <span class="kw">nullptr</span><span class="op">;</span></span>
<span id="cb45-3"><a href=""></a><span class="dt">int</span><span class="op">*</span>  p2 <span class="op">=</span> <span class="kw">nullptr</span><span class="op">;</span></span>
<span id="cb45-4"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span>p1<span class="op">)</span> <span class="op">&lt;&lt;</span> <span class="st">" "</span> <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span>p2<span class="op">);</span>  <span class="co">// Same size (8 on 64-bit)</span></span>
<span id="cb45-5"><a href=""></a></span>
<span id="cb45-6"><a href=""></a><span class="co">// Array of structs</span></span>
<span id="cb45-7"><a href=""></a><span class="kw">struct</span> Point <span class="op">{</span> <span class="dt">int</span> x<span class="op">;</span> <span class="dt">int</span> y<span class="op">;</span> <span class="op">};</span></span>
<span id="cb45-8"><a href=""></a>Point pts<span class="op">[</span><span class="dv">100</span><span class="op">];</span></span>
<span id="cb45-9"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span>pts<span class="op">);</span>                     <span class="co">// sizeof(Point) * 100</span></span>
<span id="cb45-10"><a href=""></a></span>
<span id="cb45-11"><a href=""></a><span class="co">// sizeof does not evaluate its argument</span></span>
<span id="cb45-12"><a href=""></a><span class="dt">int</span> i <span class="op">=</span> <span class="dv">0</span><span class="op">;</span></span>
<span id="cb45-13"><a href=""></a>cout <span class="op">&lt;&lt;</span> <span class="kw">sizeof</span><span class="op">(</span>i<span class="op">++);</span>  <span class="co">// i is still 0 after this</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- Appendix Slide 3 -->
</section>
<section id="practice-problems-8" class="slide level2">
<h2>Practice Problems</h2>
<ol type="1">
<li>Write a program that prints the size of every fundamental type on your machine.</li>
<li>Create a struct with a <code>char</code>, an <code>int</code>, and a <code>double</code>. Print <code>sizeof</code> for the struct. Is it the sum of the members? Why or why not?</li>
<li>Declare <code>int arr[20]</code> and use <code>sizeof</code> to compute the number of elements without hardcoding 20.</li>
<li>Predict: what does <code>sizeof("hello")</code> return? Why is it not 5?</li>
</ol>
<!-- Appendix Slide 4 -->
</section>
<section id="ai-search-terms-8" class="slide level2">
<h2>AI Search Terms</h2>
<ul>
<li>“C++ sizeof operator compile time”</li>
<li>“C++ struct padding alignment memory layout”</li>
<li>“C++ sizeof array element count idiom”</li>
<li>“C++ pointer size 32-bit 64-bit”</li>
<li>“C++ sizeof vs std::size container”</li>
</ul>
<!-- Appendix Slide 5 -->
</section>
<section id="questions-for-reflection-8" class="slide level2">
<h2>Questions for Reflection</h2>
<ul>
<li>Why does the C++ standard not mandate fixed sizes for <code>int</code> and <code>long</code>?</li>
<li>If you are writing a binary file format, why must you use fixed-width types rather than <code>int</code>?</li>
<li>What are the performance implications of struct padding, and when would you remove it?</li>
</ul>
<!-- Appendix Slide 6 -->
</section>
<section class="slide level2">

</section></section>
<section>
<section id="key-takeaways" class="title-slide slide level1 center">
<h1>Key Takeaways</h1>
<ul>
<li>The compiler checks types at compile time — most errors you can make with data types are caught before the program runs.</li>
<li>Signed integer overflow is undefined behavior. Unsigned overflow wraps predictably.</li>
<li>Use <code>static_cast&lt;&gt;</code> for intentional conversions. Integer division truncates — cast one operand to get a decimal result.</li>
<li>Default to <code>int</code>; use <code>size_t</code> for indices and sizes; use fixed-width types when exact bit width matters.</li>
</ul>
</section>
<section class="slide level2">

</section></section>
<section id="next-time" class="title-slide slide level1 center">
<h1>Next Time</h1>
<ul>
<li>Strings in depth: <code>string</code> operations, input, and manipulation</li>
</ul>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>CISP 360 · Fowler</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="p360_lecture_09.01_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="p360_lecture_09.01_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="p360_lecture_09.01_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="p360_lecture_09.01_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="p360_lecture_09.01_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="p360_lecture_09.01_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="p360_lecture_09.01_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="p360_lecture_09.01_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="p360_lecture_09.01_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="p360_lecture_09.01_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'h.v',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'default',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 5.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <script>
    window.Reveal.on('ready', event => {
      Reveal.configure({
        keyboard: {
          34: 'down',
          33: 'up',
          116: 'right',
          190: 'left',
          79: null
        }
      });
    });
    </script>
    

</body></html>