# Code This: Complete Example

**Estimated Time:** 40 minutes

## Problem Description

Write a program that helps you organize the elements of a vector.


## Requirements

1. Write function prototypes for all functions.
2. Implement all function definitions below main().
3. Use for-each loops.



## Sample Output



```

```

## Your Task

- using a for-each loop initialize the contents of a 10 element vector with random numbers between 1 - 20.

- Display the entire vector.

Your task is to eliminate all odd numbers from the vector. You can only transform a number once and you can not have any duplicate even numbers.

- Using a for-each loop, display the current element and
   - display a menu of transformations to that element
      - add 1 to it.
      - subtract 1 from it.
      - do not change it (and move to the next element)
- step through this process until you reach the end of the vector.


## Starter Code Structure


## Tips

```cpp
bool isEven(int number) {
    return number % 2 == 0;
}
```

This returns `true` if even, `false` if odd.

## Challenge (Optional - if you finish early)

- Check to see if all odd numbers were eliminated from the vector.
- Check to see if there are no duplicate even numbers. Hint: you may want to sort() this vector to make this task easier.

