
# The main Function


::: notes
~7
:::


## main()

```{.cpp code-line-numbers="8|16"}
// intro.cpp
// Dr. Fowler
// 1/1/26
// CISP360 introductory program.
#include <iostream>
using namespace std;

int main()
{
    int age = 25;
    string name = "Pat Smith";

    cout << "I'm " << name << ", age: " << age << endl;
    cout << "I love to code!\n";

    return 0;
}

```

---

- Every C++ program starts execution in main
- main is a function
- The return type is int

---

## main()
### Why does main return an int?

- The return value is sent to the operating system
- 0 means successful execution
- Non-zero values indicate errors

---

## main()
### Statements inside main

```{.cpp code-line-numbers="8-16"}
// intro.cpp
// Dr. Fowler
// 1/1/26
// CISP360 introductory program.
#include <iostream>
using namespace std;

int main()
{
    int age = 25;
    string name = "Pat Smith";

    cout << "I'm " << name << ", age: " << age << endl;
    cout << "I love to code!\n";

    return 0;
}

```

- Statements execute top to bottom
- Each statement ends with a semicolon
- Output is sent to the terminal

---

## Curly braces define blocks

```{.cpp code-line-numbers="9|17"}
// intro.cpp
// Dr. Fowler
// 1/1/26
// CISP360 introductory program.
#include <iostream>
using namespace std;

int main()
{
    int age = 25;
    string name = "Pat Smith";

    cout << "I'm " << name << ", age: " << age << endl;
    cout << "I love to code!\n";

    return 0;
}

```

---

## Curly braces define blocks

- Curly braces define a block
- Blocks control scope and lifetime
- Making blocks communicate with each other is a challenge
- Not all languages do this. Python uses indentation, for example.


---

## Key takeaways

- C++ programs have a predictable structure
- Execution always begins in main
- Structure comes before complexity
- Understanding structure makes debugging easier
